css/redactor.css
Tested with 1.9.4 - found no other / related / new issues due to this change of the z-index.
Fixes: https://github.com/osTicket/osTicket-1.8/issues/980
Fixes: https://github.com/osTicket/osTicket-1.8/issues/1411
=> UI: Fix datepicker vs. redactor toolbar z-index issue

include/class.ticket.php
Reverts osTicket/osTicket-1.8#1509
Staff initiated new tickets should not be considered automated responses.
=> Revert "Disable auto-responses on staff created tickets"

include/class.misc.php
`Misc::randCode()` does not generate significantly random data for Windows platforms with a local database. This stems from the random seed using the milliseconds from the current time of day and the database connection time, in microseconds. Because Windows™ has especially poor sub-second time resolution via the `microtime()` function, the seed does not have many variations.
This patch addresses the issue by using the included `Crypto::random()` function as a source of random data rather than the `mt_rand()` function, as it uses native cryptographic random data generators if possible to generate the data, and uses `microtime()` as a fallback if no other source of random data is available on the platform.
Also `.` characters are not allowed on the left hand side of the `@` char in email …
=> Fix very predictable random data on some platforms

include/class.ostsession.php, include/class.usersession.php, logout.php, scp/logout.php
This patch sends updated session cookies to the browser when the session is refreshed on the server. This allows the session cookie to expire on the browser at the same time the session timeout occurs at the server. In the event the session timeout is configured in osTicket not to expire, the cookie will expire after seven days on the client browser, and will expire in PHP when it is garbage collected sometime after 86400 seconds after the time last refresh time.
Using this method, the session will never expire if the session timeout in osTicket is configured to 0, and the session is refreshed at least daily.
This patch also forces the client to delete the cookie at logout.
=> Session never expires

include/class.csrf.php, login.php, scp/login.php
This patch fixes a vulnerable scenario, where sequential login attempts can be made without an existing session, and without a valid CSRF token. This scenario lends itself well for brute force password attempts, because attackers can avoid using a session and still send requests to determine if a set of credentials are valid. This vector also avoids the authentication lockout mechanism, because it requires an ongoing session to shutdown the requests.
This patch addresses the issue by requiring a session and a valid CSRF token generated by the server and placed in the session to be submitted with the credentials. Therefore, an existing session and a Cookie header are required to process a login attempt. Secondly, the CSRF token will be changed on the server after each login processed. …
=> login: Require CSRF token to login

include/staff/filters.inc.php
Fixes the missing icon before "Add new filter" in scp at the filters.php page.
Guess it was some copy and paste thing ;)
=> [FIX] Missing icon before "Add New Filter"

js/filedrop.field.js
Also, give a "Browser not supported" error for browsers which do not support the Blob constructor.
Maybe fixes #1746
References:
http://caniuse.com/#feat=blobbuilder
=> filedrop: Support Firefox down to v6

include/ajax.content.php, include/class.page.php, include/staff/settings-access.inc.php, include/staff/templates/content-manage.tmpl.php
Allow the staff banner to be set to empty (which is the default).
Also display the update errors back on the dialog for failed updated.
Maybe fixes #1775
=> access: Allow empty staff banner. Show update errors

include/ajax.draft.php, include/class.draft.php, js/redactor-osticket.js
Previously, any draft would be identified — even if it isn't owned by the current user. Then, when the draft would attempt to be updated, the update would be refused and the annoying draft saved popup would appear.
=> draft: Find the draft corresponding to your user id

include/class.thread.php
If the system receives an email by a collaborator which has not yet been added to the ticket (a friend of a friend — that is, a collaborator forwards an email to a third-party), a header is added to the thread body something like:
```
Received From: afriendofafriend@anothercompany.tld
```
However, if the thread body is text and the HTML ticket thread is enabled, then the text formatting hint will be lost and the body will be assumed as HTML deeper inside the thread entry creation process. Therefore, the whitespace inside the resulting thread entry will be collapsed.
This patch addresses the issue by maintaining the original format hint with the thread body.
=> oops: Fix corruption of thread body posted by collabs

include/class.mailer.php, include/class.staff.php
* Fix matching of collaborators on return emails. Previously the collaborator ID was used instead of the related user ID. Also, the 'C' user class (collaborator) was not handled in ::decodeMessageId()
* Only send a reply separator for email related to a thread
* Always generate a tag for the email message id. This will allow reply from the help desk administrator for the new ticket alert
=> thread: Fix a couple issues with email message-ids

include/class.export.php, include/class.forms.php
If the ticket details form has an extra field of type "Priority Level" (beyond the one built in), exports of tickets to CSV will be empty.
This patch addresses the issue in the exporter which uses an older version of the custom data materialized view (cdata table), which created separate columns for selection and ID values. The current cdata system only creates a single column and stores the ID value. 
It also addresses an issue where the ID column was passed to the `PriorityField::to_php()` as the first argument, which prevented correct values in the export.
It also allows for multiple priority fields to specify differing defaults, and it also allows for a selection of 'System Default' in the config, which renders as 'Default' when rendered.
=> priority: Fix empty export and default selection

include/class.orm.php, setup/cli/modules/class.module.php, setup/cli/modules/file.php
This patch adds an export+import method to the file command line module. The file export is agnostic of the file storage backend. It writes the files with the %file record data to standard-out or to the file given by the -f option. The file is a considered a stream and can quietly be compressed and can be read back in as a stream (no seeking is performed in the import process).
Export all files from your helpdesk (as a backup)
```
php setup/cli/manage.php file export > osticket-files.dat
```
Import the backup some time later
```
php setup/cli/manage.php file import < osticket-files.dat
```
=> file: Add import/export support

include/staff/user-view.inc.php
See: http://osticket.com/forum/discussion/85083/osticket-sends-no-html-mails#latest
Looked at crowdin and the term "Add Organization" is already used in the following context:
#: include/staff/templates/org-lookup.tmpl.php:82
So my suggestion is to use it also for this context here, which would not require a new translation ;)
Michael
=> i18n: Missing translation "Add Organization"

include/staff/departments.inc.php
Its a Agents table. For good translation the column of agents must have the name "Agents"
=> wording: must be agents, because its agents table

scp/tickets.php
This fixes a slight regression, where, if the locking mechanism were disabled, then tickets could no longer be responded to.
=> oops: Allow the ticket lock feature to be disabled

include/class.filter.php
This will help when saving rules with trailing spaces for instance, which may make things not match when visually the administrator would otherwise expect the filter to match.
=> filter: Trim match values when saving rules

include/class.dynamic_forms.php
For a yet unknown reason, the association between the field implementations and the DynamicFormEntry object is not maintained from calls to DynamicFormEntry::getFields().
This patch addresses the issue by always associating the "form" when returning from ::getFields()
=> oops: Fix dropped custom data from API requests

include/upgrader/done.inc.php
Hey guys,
just found out that the link here is not working: scp/settings.php
The full link looks like: http://my-server.com/osticket/scp/scp/settings.php
First I thought that the leading slash is missing, but this resulted also in a not working link: /scp/settings.php
The full link misses the "osticket" directory: http://my-server.com/scp/settings.php
Finally I decided to just use "settings.php" which worked and showed a correct link:
http://my-server.com/osticket/scp/settings.php
Greetings
Michael
PS: Don't know if it should be just "settings.php" - but that is working ;)
=> Upgrader done.inc.php: scp/settings.php not working

scp/js/scp.js
This addresses the issue where the advanced search dialog was submitted before the date picker inputs were fixed up. This problem arises out of a difference between the agent's date formatting preference and the server being able to process that date format. The date pickers are reformated to yyyy-mm-dd before submission; however, for advanced search, the submission happened before the inputs were fixed up.
This patch addresses the issue by manually fixing up the date in the submission routine for the advanced search dialog.
Maybe fixes #901
Maybe fixes #690
Maybe fixes #1499
=> search: Fix search on create date

include/ajax.config.php, include/class.nav.php, include/staff/templates/navigation.tmpl.php, scp/js/dashboard.inc.js
This patch addresses the issue where PJAX permanently breaks the loading order of scripts. Therefore the Raphael library currently used for the graph visualization is not loaded properly with PJAX. Therefore, PJAX is simply disabled on the dashboard page.
This also properly implements pagination for the statistics detail tabs, which seems to have been broken along the development trail somewhere.
Fixes #1853
Fixes #1828
=> dashboard: Fix initial page load and stats pagination

include/class.export.php
Because CSV has no way of indicating a content character set, writing the file with a Unicode byte-order mark is useful to declare the content in UTF-8 encoding.
Fixes #1526
=> csv: Add UTF-8 BOM to export file

include/class.dynamic_forms.php, include/class.forms.php
Add a text box widget to selection field. It functions like typeahead and drop down widgets with the exception that the user doesn't get the hint. This is useful when an internal list needs to be used to validate user's input e.g serial numbers.
=> forms: Add Textbox Selection Widget

include/class.ticket.php
When sending alerts to agents, consider the setting of the new message alert configuration.
Fixes #1849
=> alerts: Consider "alert assigned on new message"

include/class.api.php, include/class.mailfetch.php, include/class.mailparse.php
Here's an example email structure:
```
multipart/mixed
- multipart/report; delivery-status
- multipart/alternative
- text/plain
- text/html
- message/delivery-status
- message/rfc822
```
The previous code would only find the body if the email main headers had: `Content-Type: multipart/report; report-type="delivery-status"`. In such a case it would scan for a plain/text body.
This patch will scan for the usual body if the scan for the body as usual if the report scan did not find anything.
Also, output errors to stderr when running API from the command line
=> email: Some bounce notices actually have rich content

include/class.mailer.php, include/ost-sampleconfig.php
It seems that most systems handle the newline character alone without a problem; however, some systems cannot handle the standard CRLF line ending at all.
=> email: Use \n as the default line ending

include/class.mailfetch.php, include/class.mailparse.php, setup/test/tests/test.header_functions.php
This also adjusts the logic internally to lookup the priority by the `priority_urgency` field, which should be constrained to follow priority precedence over the `priority_id` field.
Maybe fixes #1674
=> email: (Correctly) parse priority to priority_urgency

include/class.config.php, include/class.thread.php, include/class.ticket.php, include/i18n/en_US/help/tips/settings.alerts.yaml, include/i18n/en_US/templates/email/note.alert.yaml, include/pear/Mail.php, include/staff/settings-alerts.inc.php
This adds the ability of the system to notify agents when another agent replies to a ticket. This is implemented by extending the "New Internal Note Alert" to also include replies by agents. The same alert settings will be applied to both alerts — new internal notes and new replies.
=> Agent internal activity alert

include/class.email.php, include/staff/email.inc.php
This patch adds an error to the page if unable to configure the archive folder and POP was selected as the mailbox protocol. Generally, POP servers do not support anything but the INBOX
=> email: Add warning for archive folder for POP

include/class.dept.php, include/class.ticket.php, include/i18n/en_US/help/tips/staff.department.yaml, include/staff/ticket-view.inc.php, scp/tickets.php
Unassign tickets on transfer when the target department has assignment restriction and the assigned staff is not a member. Also disable claim (quick self-assignment) when the restriction is in effect.
=> Unassign on transfer

include/class.dynamic_forms.php, include/class.ticket.php
When the user is not identified by the web interface, such as processing email to tickets, attempt to locate and include the user filter information when matching the filter to the new ticket data.
Maybe fixes #1937
=> filters: Filter user information for email tickets

include/class.mailer.php
Ensure that the References header that is included with outbound email definitely includes the References header from an email received into the system, if at all possible.
Maybe Fixes #1346
=> mailer: Try harder to find References header

include/class.dynamic_forms.php
If an update to an object such as a ticket results in a corresponding update to the CDATA table, and one or more of the fields have been deleted from the ticket details form, then, avoid updating the CDATA table for those fields.
This fixes an issue where the CDATA table is dropped and recreated when fields are added and removed from the form. The table will only contain fields which are currently on the form when the table is created. Therefore, deleted fields will never be on the CDATA table and will result in an SQL error.
=> forms: Don't update CDATA when updating old fields

bootstrap.php, include/class.company.php, include/class.draft.php, include/class.dynamic_forms.php, include/class.forms.php, include/class.list.php, include/class.organization.php, include/class.orm.php, include/class.sequence.php, include/class.task.php, include/class.thread.php, include/class.translation.php, include/class.user.php, include/staff/dynamic-form.inc.php, include/staff/templates/dynamic-form.tmpl.php, include/staff/templates/form-manage.tmpl.php, include/staff/templates/org.tmpl.php, include/staff/templates/user-delete.tmpl.php, include/staff/templates/user-lookup.tmpl.php, include/staff/templates/user.tmpl.php, include/staff/ticket-view.inc.php, include/upgrader/streams/core/b26f29a6-1ee831c8.patch.sql, scp/forms.php, scp/lists.php, setup/test/run-tests.php, setup/test/tests/mockdb.php, setup/test/tests/test.header_functions.php, setup/test/tests/test.mail-parse.php
This feature addresses a major issue with the initial implementation of the custom data system. The original system confused the usage of database-backed field (dynamic-fields) and their corresponding implementation. This created the need to crate awkward caching pieces to ensure that validation errors and data was maintained. Furthermore, the system confused the linking between form instances (dynamic-entry) and the form used to represent that entry.
This patch addresses the confusion in two ways:
Dynamic form entries do not link directly to the dynamic form. Instead, the ::getForm() method returns something from the forms API directly. Furthermore, the ::getFields() method does not return dynamic field instances (database backed / designed fields). Instead, the actual implementation of …
=> Feature :: Dynamic Forms 1.1 — address major confusion and magic issues

include/class.format.php, include/class.mailer.php, include/class.thread.php
Several mail clients do not return the Message-ID header in a In-Reply-To or References header as they should. The assumption by such mail clients is that the email be threaded based on the Subject header. However, osTicket does not require the ticket number to be placed in the Subject header and so has trouble threading email from such systems. osTicket embeds a copy of the Message-ID header (or compatible version) in the body of the message in hopes part of the message will be returned.
Many mail clients (such as osTicket) strip and clean the HTML when processing HTML email. Previously, the message-id token was embedded in a @data-mid attribute, which was likely stripped before the HTML email would be returned back to osTicket.
This patch suggests that the token be placed in a @class …
=> mailer: Embed the Message-Id token in @class

include/class.export.php
For locales which use comma as the decimal separator, CSV exports should be generated using a semi-colon (;) rather than a comma (,) since spreadsheet programs in such locales will have difficulty with comma-delimited CSV files.
=> i18n: Consider current locale for CSV delimiter

include/class.mailfetch.php, include/class.mailparse.php
This correctly handles a bounce message with the following layout:
```
multipart/report; report-type=delivery-status
multipart/alternative; differences=Content-Type
text/plain; charset="us-ascii"
text/html; charset="us-ascii"
message/delivery-status
message/rfc822
```
=> email: Properly detect bounce message with alternative content

include/class.auth.php, include/class.staff.php
This adds the concept of a PasswordPolicy registration system, which provides an extensible way of administering and configuring password complexity policies.
It also adds a setPassword() method for the authentication backends which will allow for the respective backend up update the password according to whatever method is suitable for the respective backend (such as remote updates for LDAP).
I'll open a concept plugin to take advantage of this feature (osTicket/core-plugins#60)
=> auth: Add concept of bk passwd update and policy

include/class.ticket.php
Preserve text formatting on the internal note posted to a new ticket by staff if HTML thread is disabled.
=> html: Ensure text internal note preserved

include/class.charset.php
This is necessary for some mail clients which indicate encoding in GB2312 but actually use GBK encoding.
=> i18n: Translate gb2312 to gbk charset

include/class.dynamic_forms.php, include/class.user.php
This patch adds a feature to the import process, so that if a user already exists (identified by its email address), then the name and other custom data are updated with the information in the CSV record being imported.
=> users: Update information on CSV import

include/class.format.php
Copy+Pasting images from a ticket thread or from a FAQ article to the HTML editor and submitting will result in the URL *not* being properly rewritten for storage in the database. When images are uploaded, a relative URL is returned from the server and embedded in the HTML editor. However, when images from the system are copy and pasted into the editor, an absolute URL with the http:// scheme is included. This URL was not properly handled by the URL rewriter in Format::localizeInlineImages().
This patch addresses the issue by properly handling both relative URLs from image uploads and absolute URLs from copy and pasting.
Maybe fixes #334
=> Fix image CID rewrite for some pasted images

include/staff/filter.inc.php
Follow-up PR to the comment here:
https://github.com/osTicket/osTicket-1.8/commit/06d3a0f3e2a4557ca72faa916859b9315635dfe4
=> oops: Fix bad HTML entity #2

include/i18n/en_US/config.yaml, include/upgrader/streams/core/b26f29a6-1ee831c8.cleanup.sql, include/upgrader/streams/core/b26f29a6-1ee831c8.patch.sql, setup/inc/class.installer.php, setup/inc/footer.inc.php, setup/inc/header.inc.php, setup/inc/install.inc.php, setup/js/setup.js
=> Set system default timezone to Olsen on upgrade

include/class.dynamic_forms.php, include/class.forms.php, include/class.list.php
Support using value or abbreviation for choice/selection input fields. API calls can now use list value or it's abbreviation instead of internal numeric IDs.
For example API calls can now us "LA" or "Louisiana" as input for a state list field.
=> forms: Add choice lookup support

setup/cli/modules/deploy.php
=> fast fix for deployment on windows #2032

include/upgrader/streams/core/435c62c3-2e7531a2.patch.sql, include/upgrader/streams/core/c00511c7-7be60a84.patch.sql, include/upgrader/streams/core/d0e37dca-1da1bcba.patch.sql
If osTicket was improperly or incompletely upgraded, then some tables may exist which should otherwise not exist. This patch assists the upgrade process by dropping the tables which should not exist prior to adding or renaming tables.
=> db: Drop tables before adding and renaming

include/class.ostsession.php, include/ost-sampleconfig.php, scp/autocron.php
This adds support for Memcache server(s) as a session storage backend. This is useful for higher traffic sites as it removes a database write per request. Therefore, read requests can be truly read; without database writes. Multiple Memcache servers are supported and used redundantly so that as long as at least one Memcache server remains reachable, session data will not be lost before it expires.
=> session: Add support for Memcache as a session backend

include/class.forms.php, include/class.staff.php, include/class.validator.php, include/staff/ticket-view.inc.php, scp/banlist.php, scp/emailtest.php, setup/install.php
This allows detection of some incorrectly-typed email addresses before tickets, users, and agents are created.
It also adds a warning to the ticket view page to alert agents of invalid, in-use email addresses. This may happen for emails processed into tickets when the `Reply-To` header is used, as well as for old tickets created before this patch.
=> validator: Verify MX record of email addresses

include/class.dynamic_forms.php, include/class.forms.php, include/class.plugin.php
Also, fix roundtrip encryption if the form name changes (which is based on a user's session), and avoid saving a NULL value if the password is not changed when a form is updated.
=> forms: Show ••• placeholder for saved pw entries

include/class.search.php, include/class.thread.php
* Reindexing did not properly flush the last batch of items to the search therefore reindexing would always miss the last few items.
* Creating a new html thread entry with inline images resulted in empty search content
* HTML tag stripping in HtmlThreadBody::getSearchable() would result in missing white space between some words, resulting in poor searchable content
=> search: Fix several small issues with search indexing

include/html2text.php
Here's an example email with the new system:
```
DEAR JÄRED,
───────────
Our customer care team has created a ticket, [#̲7̲3̲0̲8̲6̲1̲][1] on your behalf,
with the following details and summary: 
Topic: ACCESS ISSUE 
Subject: ZUGANGSPROBLEM 
If need be, a representative will follow-up with you as soon as possible.
You can also [v̲i̲e̲w̲ t̲h̲i̲s̲ t̲i̲c̲k̲e̲t̲'s̲ pr̲o̲gr̲e̲s̲s̲ o̲n̲l̲i̲n̲e̲][1]. 
Your Jared's Helpdesk Team,
Jared Hancock
IT Mastermind
klopen Graphics, Inc.
──────────────────────────────────────────────────────────────────────────
If you wish to provide additional comments or information regarding the  
issue, please reply to this email or [l̲o̲gi̲n̲ t̲o̲ yo̲u̲r̲ a̲c̲c̲o̲u̲n̲t̲][1] for a   
complete archive of your support requests.
-------------------------------------
[1] …
```
=> Make a couple improvements on the html -> text system

include/class.attachment.php, include/class.forms.php, include/class.mailer.php, include/class.thread.php, include/client/templates/thread-entry.tmpl.php, include/staff/templates/thread-entry.tmpl.php, include/upgrader/streams/core/9143a511-00000000.patch.sql, js/filedrop.field.js, setup/inc/streams/core/install-mysql.sql
This patch (which may need further development), introduces an extra field to the %attachment table to store a file's name in the event that two files with the same content are stored in the database with differing names. In such a case, the name is stored in the %attachment table. This allows the attachment to specify a different name each time the same file is attached to something in the system.
It also would allow the file's name to be edited after attaching, and it would not affect any other attachment's names with the same, deduplicated content.
=> file: Allow different names for duplicated content

include/class.forms.php
This fixes the inability to save the search user password in the LDAP or S3 plugins
=> forms: Fix fail getting value of password field

include/class.format.php
9ae01bf208060528a05164d22817e776fa75c7ef turned off HTML balancing, however, quoted response removal will create unbalanced HTML. That HTML will be stored unbalanced and will require extra processing when displayed on the ticket thread.
This patch adds balancing support using libxml if enabled, which will balance HTML without corrupting the HTML like htmLawed will with balancing enabled.
=> html: Balancing is important

include/class.ticket.php
This patch will help ensure that if a ticket is not reopened on a message (perhaps because of a out-of-office auto-reply from an enduser), then the closing agent on a closed ticket should not be cleared.
=> Ensure OoO message does not clear closing agent

include/class.signal.php
When using call_user_func_array arguments should be passed by reference in order to allow callable receive them by reference (only defining callable to receive data by reference is not enough).
=> Pass data to the callabale by reference

include/class.mailer.php
When the php mail function is used to send email, this change adds error logging if an error is detected by PEAR
=> log php mail error

setup/cli/modules/class.module.php, setup/cli/modules/deploy.php, setup/cli/modules/unpack.php
This fixes a regression in the option parsing where --setup would be interpreted as --setup -e -t -u -p
Also, some parts of osTicket, like internationalization and plugins need read access to a directory in order to get a list of installed plugins and language packs.
Fixes #2196
=> cli: Fix incorrect option parsing

include/class.variable.php
The DomDocument::saveHtml() method will properly urlencode() values in the a[@href] attributes when saving. This patch allows for the sanitization while also allowing the variable replacement system to work properly with the sanitized values.
Fixes #2201
=> variable: The HTML balancing system urlencodes @href

include/class.orm.php, include/class.upgrader.php, include/cli/modules/upgrade.php
This patch adds the ability to trigger an upgrade from the command line
```sh
php manage.php upgrade
```
And can hopefully help with recovering failed upgrades in the future.
=> cli: Add concept of cli applet to upgrade

README.md, include/class.file.php, include/cli/modules/file.php, include/upgrader/streams/core/15b30765-dd0022fb.patch.sql, include/upgrader/streams/core/15b30765-dd0022fb.task.php, include/upgrader/streams/core/934954de-f1ccd3bb.patch.sql
This patch suggests that old attachments in the `upload_dir` can be located and left alone when upgrading away from osTicket v1.6. Later, via the `file` command line applet, the attachments can be migrated into the database, or to the new filesystem plugin after it is installed with:
php manage.php file migrate --backend=6 --to=D
This allows attachment migration to be retried in the event it failed for any reason. Of course, installed storage backends can be listed with `php manage.php file backends` and more help is available with `php manage.php file -h`
=> upgrade: Defer migrating attachments from v1.6

include/class.search.php
This patch automatically configures reindexing of the search table when the table is dropped and recreated.
Fixes #2208
=> search: Auto reindex when _search is created

include/class.organization.php
If a user is created with an empty domain name (e.g. `<user@>`), then the user would be associated with the first organization without a main domain specified.
This patch ensures that the domain is not empty when making a match with an organization.
=> org: Fix matching of empty domain name

include/class.config.php, include/staff/header.inc.php
This will break the browser cache and refresh the selected logo on save.
The default logo displayed on page.
Custom logo is selected and on save immediately displays selected logo in the header.
Custom logo is displayed in the header after save.
* After the custom logo is saved selecting the default logo again and saving does NOT change on save. It does change on refresh.
=> Changed logo displays on save

assets/default/css/theme.css, include/client/tickets.inc.php, include/client/view.inc.php, include/staff/ticket-view.inc.php, include/staff/tickets.inc.php, js/osticket.js, scp/css/scp.css, scp/js/scp.js
If the subject field is something crazy, such as an HTML field, ensure that the layout of the ticket queue is preserved and properly truncated. Furthermore, ensure that the HTML is properly rendered on the client and staff ticket view pages.
=> tickets: Fix subject display for non text fields

scp/css/scp.css
Issue with select list options pushing below the viewable select box in firefox. giving the appearance of being cut in half.
Before:
After:
And rounded corners on inputs for firefox as an added bonus.
=> Firefox form style fix

include/ajax.orgs.php, include/ajax.tickets.php, include/ajax.users.php, include/class.search.php, include/staff/tickets.inc.php, scp/js/bootstrap-typeahead.js, scp/js/scp.js, scp/tickets.php
This patch fixes the sticky queue system. For instance, performing an advanced search does not always end up serving the search results on the next request. A second click on the "Search" queue might be required to actually view the results..
The typeahead in the basic search uses full-text search, which is about 10x faster than the index and full-table scans previously employed. Numbers are treated as ticket numbers along with full text search. Hits on ticket numbers are preferred in the typeahead results automatically. 
Scrolling is employed in the typeahead rather than limiting at 8 hits. 25 hits are displayed at most.
Searching for email addresses can be confusing, and the at sign (@) is completely ignored by the full-text backend. However, using a few words rather than the email …
=> search: Improve typeahead results and performance

include/class.file.php
When saving an attached file in the database, Passing the whole content of the file to bin2hex leads to allocating the memory for the whole hex encoded file while the binary content of the file is still in memory. This leads easily to Out of memory error on limited resources servers. Calling bin2hex on each chunk of the file greatly limits the memory usage.
=> reduce memory usage when storing file in DB

include/class.mailer.php, include/class.mailparse.php, include/class.task.php, include/class.thread.php, include/class.ticket.php
This patch changes the way the thread entry type and other properties are determined by using the `userClass` determined in the `Mailer::decodeMessageId` method which is preferred over the older heuristic methodology using the `From` email address alone.
It also includes the work of and builds off of Peter's pull request in #2529
=> Fix posting-user determination in Thread::postEmail

account.php
We have existing clients who do not have an account (yet) on osTicket.  We create a ticket for them from the admin interface (creating a new guest user account) and this results in an email being sent to them with details of a job carried out.  This user can then click on the link in the notification email and view the ticket as guest - and hopefully opt to register an account.
The problem seems to be this - the user clicks on the ticket number in their notification email which lets them view the ticket as a guest - there is then a link to 'register for an account' linked to http://www.example.com/account.php?do=create - but clicking this link results in a blank page.  The PHP error is:
PHP Fatal error:  Call to a member function getField() on a non-object in …
=> Blank page from 'register' link in notification email to guest user.

include/class.api.php, include/class.cli.php, include/class.osticket.php, include/cli/cli.inc.php, include/cli/modules/unpack.php, manage.php
The new deployment system will crash from a repo without a config file because it always calls Bootstrap::loadConfig(), which will crash in none exists. Furthermore, calls to osTicket::is_cli() result in some garbage output which gets written to the deployed `bootstrap.php` where INCLUDE_DIR is defined.
=> Fix issues deploying with PHP 5.6

include/class.client.php, include/class.nav.php, include/class.organization.php, include/class.orm.php, include/class.ticket.php, include/class.user.php, include/client/tickets.inc.php, include/i18n/en_US/help/tips/org.yaml, include/staff/templates/org-profile.tmpl.php, tickets.php
This feature allows (by option) an organization to allow its members to see tickets from other members. It can be used beside or instead of the automated collaboration feature. Now, collaborators retain access to tickets on which they participate; however, sharing can be used to enable access to other tickets owned by their organization.
=> orgs: Add ticket sharing feature

include/class.mailfetch.php
When decoding attached files, passing the whole content of the file to imap_base64 or base64_decode leads to allocating the memory for the whole base 64 decoded file while the binary content of the file is still in memory. This leads easily to Out of memory error on limited resources servers. Using .stream_filter_append to decode the file while writing it in a temporary file uses much less memory. The content of the decoded file is then simply read from the file
=> reduce memory usage when decoding files

include/class.orm.php
... and some of the related models are null.
=> orm: Avoid crashing when building a model with select_related

include/class.forms.php
This fixes a security issue where, by crafting a special POST request to the client open.php page, an (unauthenticated) user could get a URL link to access to any attachment already uploaded in the system by guessing or brute-forcing the file's ID number.
This patch addresses the issue by registering the uploaded file's ID in the current user's session. When processing the list of file ID's attached to the FileUploadField, the files must already have been attached to the field or have been newly attached in the current session.
Fixes #2615
References:
"Security issue - Download attachments submitted by others"
https://github.com/osTicket/osTicket-1.8/issues/2615
=> files: Verify files attached to a FileUploadField

include/staff/templates/tickets.tmpl.php, include/staff/tickets.inc.php
Fixes a bug where a lock icon is shown on tickets listing even when the lock in question is expired.
=> locks: Exclude expired locks via constrain

scp/login.php
This fixes a bug where the browser will fail to redirect away from the login page if the client's browser doesn't allow for location mutations with the 422 response code. This was triggered since there was no exit call after the bare header mutation. Using the HTTP#redirect call solves this problem.
This issue only impacted SSO auth plugins.
=> Fixes bare header redirect

css/filedrop.css
Sets a static height to the row since it truncates it shouldn’t have
any odd behavior. Content in the span is centered on the row and sets
image height to fit inside the row.
Before:
After:
=> Uploaded image preview fix

include/class.dynamic_forms.php
MySql 5.6 and MariaDB 10 will return affected_rows == 0 if updating a row to its current values. Therefore, if an object is "edited", but none of the CDATA is modified, then the CDATA table might be dropped and rebuilt.
=> forms: Avoid dropping the CDATA table

assets/default/css/theme.css
Older browser height fix for the end user avatar. Changing the height
100% property to height auto; corrects the avatar size on older
browsers, in this case Safari 5. The fix will keep the image from
stretching 100% for the end user.
=> End user avatar fix for #2557 #2580

include/ajax.orgs.php, include/ajax.tickets.php, include/ajax.users.php, include/class.search.php, include/client/tickets.inc.php, include/staff/tickets.inc.php
* Bubble search relevance from the sum of the relevance for all thread entries, users, organizations, and ticket metad-data when searching for tickets
* Only auto-promote to wildcard searches if the search query ends in a word char (letter or number)
* Only quote email addresses in BOOLEAN full-text mode. This allows for searching for partial email addresses
* Avoid using very short search queries for full-text searches
* If a full-text search results in one hit (e.g. search on ticket number), then redirect directly to the ticket view
=> Fix several search related issues

include/pear/BUNDLE, include/pear/Mail/mime.php, include/pear/Mail/mimePart.php, include/pear/Net/SMTP.php
This includes upgrades to the Mail_Mime and Net_SMTP upstream libraries. It also includes a patch to use the defined header charset (`utf-8`) for attachment filename encoding
=> Upgrade pear Mail libraries, use header charset for attachment filenames

include/class.filter.php, include/class.ticket.php
If a new message alert bounced to a staff member and the postmaster sent back a bounce notice, which was threaded, then the agent might receive another new message alert, which would continue a bounce loop.
=> bounce: Avoid a loop on new message alert to staff

include/staff/settings-alerts.inc.php
Hi guys,
had this issue in my mind from before my vacation. Someone over in the forum had the issue that even though he checked "Assigned Agent / Team" the team never got notified. After some research and a closer look I guess Neil found out that he needed to check "Team Lead" and/or "Team members" to enable alerts for the team as well.
So in this case the wording "Assigned Agent / Team" is a bit misleading and I suggest to change it to just "Assigned Agent" or whatever  you prefer ;)
Just made this pull request, so that you don't need to search long and it's (hopefully) easier to understand which "Assigned Agent / Team" is meant since it's there several times at the alert settings page.
Cheers,
Michael
PS: Also I don't know why the first line appears as "removed" and "added" ... didn't …
=> UI: Assignment alerts do NOT include teams

include/ajax.users.php, include/class.search.php
Fulltext search is not ideal for user lookup - too many MYSQL dependent variables like min-word-length stop words and characters types. This pull request makes the fulltext based user lookup optional and disabled by default until we address the limitations.
=> Make fulltext search optional on user lookup

css/redactor.css
When the overlay appears and you have previously scrolled down the page, the reactor bar appears on top of it. reactor.min.js sets an unnecessarily high z-index when the bar is appearing on top of the text box. The issue comes from this line in reactor.js: https://github.com/yiiext/imperavi-redactor-widget/blob/4d518f7b294785d3c1ec304abe38a513ebae5638/assets/redactor.js#L2472
Forcing a lower z-index on the reactor bar to fixes it. Using !important isn't a good practice but it's the only way since we can't modify the library. The latest version (10.2.5) doesn't appear to set the z-index so that will probably fix it. Could be worth looking into upgrading.
=> Fix a bug with the reactor bar appearing on top of the overlay.

include/class.mailer.php, include/class.task.php, include/class.thread.php, include/class.ticket.php
Make sure reflected email headers are valid for the recipient.
This PR addresses cases where the wrong thread participant (collaborator) is falsely credited for a message as a result of false-match due to errant in-reply-to and references headers being added haphazardly to outgoing emails.
=> bug: In-Reply-To and References headers

include/class.thread.php, include/staff/templates/thread-entry.tmpl.php, scp/css/scp.css
This is necessary to differentiate true system notes vs. notes made by deleted agent or collaborator (user). 
The change will help also make SYSTEM as a poster name translatable.
__Pending__
=> Flag SYSTEM thread entries

include/class.config.php, include/class.mailer.php, include/class.staff.php, include/class.thread.php, include/class.ticket.php, include/client/templates/thread-entry.tmpl.php, include/i18n/en_US/help/tips/settings.agents.yaml, include/i18n/en_US/help/tips/settings.ticket.yaml, include/staff/profile.inc.php, include/staff/settings-agents.inc.php, include/staff/settings-tickets.inc.php, include/staff/templates/task-view.tmpl.php, include/staff/templates/thread-entries.tmpl.php, include/staff/templates/thread-entry.tmpl.php, include/staff/ticket-view.inc.php, scp/css/scp.css
This pull requests adds two preferences to agent's profile. To avoid a database patch, global Config table is being used to store the preferences (which requires an extra lookup trip to the database after the object loads).
__Add option to use department's or agent's name on replies__
Enable the ability to use the agent's full name or department's name on responses/replies in addition to the emails address name. 
Email address of the response would still be the designated outgoing email address of the department to which the ticket/task is assigned or the system default outgoing email address.
* Agents can set the default FROM Name in Profile > Preference.
* Private department's name won't be used regardless of the setting.
* Agent's name won't be used if identity masking is enabled. …
=> Agent's preferences

include/class.config.php, include/class.thread.php, include/client/templates/thread-entry.tmpl.php, include/i18n/en_US/help/tips/settings.system.yaml, include/staff/settings-system.inc.php, include/staff/templates/thread-entry.tmpl.php
Add a global option to disable avatars on thread correspondence . Agent's and user's profiles will still show an avatars.
=> Make Avatars optional on thread view

include/class.auth.php, include/class.client.php, include/class.config.php, include/class.http.php, include/i18n/en_US/help/tips/settings.users.yaml, include/staff/settings-users.inc.php
Add ability to disable use of authentication tokens on ticket links. 
__Note__: Disabling auth-tokens effectively kills Guest Ticket Access email verification mechanism. Use of difference link variable might be necessary.
=> Make Authentication Tokens Optional

include/staff/tickets.inc.php, scp/js/scp.js, scp/tickets.php
This changes the typeahead to redirect directly from the typeahead click rather than redirecting after performing the search a second time on the ticket queue page.
Fixes #2667
=> typeahead: The redirect header was emitted too late

include/staff/tasks.inc.php, include/staff/tickets.inc.php
Column heading based sorting got removed in favor of drop down based sorting in commit
number fa327c. It's being returned due to negative feedback we received from users.
=> Columns Heading Sort

include/class.ticket.php
Auto-assign to closing staff or the last respondent if the agent is available and has access. Otherwise, put the ticket back to unassigned pool.
=> Check agent's access on reopen auto-assignment

include/class.dynamic_forms.php, include/class.forms.php, include/class.misc.php, include/staff/ticket-edit.inc.php, include/upgrader/streams/core/0d6099a6-98ad7d55.patch.sql, scp/tickets.php
This changes the storage model for datetime fields and stores them in the same format as the MySQL `datetime` column type. This allows for the searching code to be consistent when searching the database for datetime custom form entry data.
It also addresses and inconsistency in the forms code, where the PHP value of form fields was stored in the %cdata tables—instead of the normal database version. This code includes a FormField::getKeys() method to deal with multi-entry choice fields.
=> forms: Fix search by datetime fields

include/class.ticket.php
This fixes an issue, where the department manager cannot be excluded from the new ticket alert if the members of the department are checked. Considering there is a separate selection for the manager, this patch adjusts the system so the manager of the department only receives the new ticket alert if the manager checkbox is set. Otherwise, only the members of the department other than the manager receive the alert.
=> alerts: Do not include the manager with the members

include/class.export.php, include/class.orm.php, include/client/templates/thread-entries.tmpl.php, include/mysqli.php, include/staff/faq-categories.inc.php, include/staff/templates/thread-entries.tmpl.php
This adds a new concept to the ORM iteration mechanisms and allows iterating over very large queries without caching the records neither in the result set nor in the model cache. It also implies using the mysqli_query() method rather than the prepared statement model, as unbuffered queries with the prepared statement system are much slower.
This fixes an issue where exporting with 256MB of memory for PHP will limit the output to about 18k tickets maximum before memory is exhausted. With this patch, the memory used for exporting is held constant at about 9MB regardless of the number of tickets exported.
=> ORM queries avoiding caching

include/class.orm.php
This fixes a regression in 4f8f236d6a114c710362fdc302c4763cdf2fd387, where the parameters are sent in the SQL statement to the database. Objects which are converted to a string must be propertly quoted when placed in the query.
=> orm: Properly quote objects in queries

include/class.forms.php
Is is just me, or did attachments stop working altogether?
Somehow the attachment security checks got duplicated and messed up. Perhaps it was a bad merge?
=> forms: Fix attachment security merge conflict

include/class.dynamic_forms.php
This fixes an issue where the CDATA table is updated with the OLD version of an answer after it is updated. That is, after an answer is updated, the CDATA table is also updated to reflect the change; however, the old content of the answer value is used when updating the CDATA value.
=> forms: Fix lag updating the CDATA table

include/class.orm.php, include/class.staff.php
If something like `members__staff` is considered leaving the Team model, and the `members` relationship is nullable, and the `staff` relationship is not, in the context of the compiled SQL statement, the second join should also be considered nullable (LEFT join), because otherwise inconsistent results would be returned from the query.
In other words, if a count is considered as an annotation to the Team model instances, Teams with zero members should still be considered as valid teams and should be selected with such an annotation. Before this patch, however, the join between TeamMember and Staff would have been an inner join instead of a LEFT join, which could skew the database results.
=> orm: Propagate LEFT joins in join paths

include/class.mailfetch.php, include/class.orm.php, include/class.thread.php
This commit attempts to remove some of the confusing and redundant code to attach files to thread entries and replace it with a single code base. It also attempts to remove and error where a single attachment might be attached to a new thread entry multiple times.
Lastly, it removes the insert followed by an update for emails with inline images. This should improve performance processing emails as only one trip to the database is now necessary for thread entries with inline images.
Maybe fixes #3001
=> files: Attempt to standardize thread entry attaching

include/class.faq.php, include/class.orm.php, include/class.task.php, include/class.ticket.php, include/class.translation.php, include/client/templates/sidebar.tmpl.php, include/client/templates/thread-entries.tmpl.php, include/staff/templates/thread-entries.tmpl.php
This partially reverts a change in the ORM changing the QuerySet::all() method to return an Iterator rather than an array. I spent a while proposing a patch to replace usage of all() with iterations; however, I cannot propose a valid reason to abandon the previous methodology.
This reintroduces the previous behavior: calling all() will yield an array of results from the QuerySet's iteration system.
=> orm: Partially revert 8ab4432ff7

include/class.email.php
Include username when checking if an email address is a system email. This is important for emails that use aliases.
For example: help@domain.com is hosted on Office 365 - the username used to fetch emails might be help@domain.onmicrosoft.com, and should be considered a system email.
=> Email aliases

include/class.mailer.php
If the Return-Path header does not match the From header, emails are significantly more likely to be blocked by spam filters.
This patch forces the return header to match the from address without having to change php.ini and therefore works properly on servers that have multiple apps sending from multiple email addresses for example shared hosting, multiple support emails in one instance etc.
=> FIX: Return-Path header is landing in spam boxes

include/class.ticket.php
This PR addresses a bug where an agent-opened ticket doesn't set closed by or mistakenly set it to auto-assigned agent when a status of closed state is selected.
* Always credit the agent opening the ticket with close credit on closure
* Only do ticket auto-assignment IF the resulting status is in open state
=> closed-by: Credit the agent opening a ticket on close

file.php, include/class.config.php, include/i18n/en_US/help/tips/settings.system.yaml, include/staff/settings-system.inc.php
This feature adds a setting to the control panel to require signing in to view attachments. This is in addition to the security already provided in the download URLs. Currently, download URLs are signed for a specific help desk, and automatically expire after about 24 hours. (The exact timing is the following GMT midnight allowing for at least 12 hours cache time.)
Administrators can impose this extra security feature to refuse serving attachment files if the user is not currently signed in. This could prevent third-party users from viewing an attachment if they were able to get access to the download URL before it expired.
**One caveat** is that the system cannot be sure if the unauthenticated user is an end user or an agent. Therefore, if the system cannot determine the user class, and …
=> files: Require authentication to view attachments

bootstrap.php
This is required for system requests such as email piping. Since a user is not logged in for the request, the system locale will not be set and text might get corrupted based on the PHP configuration.
Fixes #2910
=> i18n: Ensure UTF-8 locale is set

include/class.i18n.php
Set default locale in `Internationalization::bootstrap()`
This PR reimplements PR #3168 which was mistakenly merged and reverted by fcd5f44b
=> i18n: Set UTF-8 as default locale

include/cli/modules/deploy.php, include/cli/modules/unpack.php
With the advent of the MANIFEST file, files which are rewritten when deployed, such as those which have the GIT hash in the query string to force browser reloading, were no longer deployed unless the content of those files changed.
This patch adds a flag to the MANIFEST file to indicate that the file was rewritten when it was deployed. This allows the file to be deployed and rewritten again when the deployment is run, but also adds an indication to the console output to distinguish deploying changes as opposed to deploying rewrites.
It also improves the exclusion mechanism for cleaning so the .MANIFEST and ost-config.php files are not cleaned from the deployment target.
Maybe fixes #3025
=> Don't clean the config file, re-deploy rewritten files

include/class.plugin.php, include/cli/modules/i18n.php, include/staff/system.inc.php, scp/css/scp.css
Since two major versions will internationalization support will soon be available, the language pack system will need a way to indicate which major version of osTicket the phrases were compiled for. This patch adds a `Phrases-Version` tag to the MANIFEST, which will be a copy of the MAJOR_VERSION included in the messages.pot file created via `make-pot`. Then, a `Build-Major-Version` tag is added to the MANIFEST which represents the version of osTicket used to compile the language pack.
It also adds a `-b` option to the `build` command for the i18n cli applet. It causes the build to use a particular branch of the Crowdin language phrases.
=> I18n language pack versioning

include/class.cron.php, scp/autocron.php
The [signal documentation](https://github.com/osTicket/osTicket/blob/develop/setup/doc/signals.md) for the `cron` signal states that the context is `null`. But it was missing until now (and the `$data` parameter was wrongly forwarded as`$object`)
=> Make `cron` signals conform to documentation.

include/ajax.tickets.php, include/class.dept.php, include/class.forms.php, include/class.orm.php
This fixes an issue where the `$ht` variable is not properly initialized by the ORM. It is assumed to be a valid array in the constructor, and its items are run through the ::set() method. Therefore, if an empty array is received, the `$ht` variable will remain null, since nothing is ever set.
This also fixes a misspelled variable in the claim dialog if a ticket is currently assigned to a team only.
It also cleans up usage of `getMembers` in class Dept. In ::isMember(), there is now no reason that a call to ::getMembers() would fail, so it can be assumed that a QuerySet instance is returned.
I also think we should merge #3090
=> orm: Fix warning for read-only role permission, cleanup Dept::getMembers() usage

include/class.orm.php
Allows for ability to access results without the need to call getIterator on the QuerySet. 
For example - ```$this->members->findFirst(array(...));```
This commit addresses regression issue brought about by commits 8ab4432f and eb0ba31 -- where ResultSet processing changed based on caching mode.
=> orm: Delegate ResultSet calls to QuerySet Iterator

include/class.dynamic_forms.php
Forms can be deleted if they have entries. Therefore, when editing entries, it should be assumed possible that the form connected to the entry may no longer exist when being edited.
This bug does not affect the v1.10 branch
Fixes #3178
=> forms: Fix crash when editing entries from deleted forms

include/class.timezone.php
The PHP 'GMT' timezone is equivalent to the 'UTC' timezone and therefore does not include summertime offsets. The 'GMT' timezone reported by MySQL, however, does use the BST summertime offsets. Therefore, the 'GMT' reported by MySQL should be explicitly translated to the 'UTC' timezone for use in PHP.
Maybe fixes #2440
=> dates: MySQL 'GMT' includes BST

include/class.format.php
This patch removes any contents of an html element when scrubbing html markup. Some markup includes complex namespaces and other information which does not concern the html processing of osTicket. It also messes up the htmLawed processing of the htmLawed.
Thanks @robintoy, @talilon
Maybe fixes #2465
Maybe fixes #2272 
Backport to 1.9.x
=> html: Fix processing of some <html> tags in email

include/class.thread.php, include/class.ticket.php
Add basic support for threading email conversations happening outside the system. Autoresponders are paused when threading is on passive mode. Alerts may still go out to agents as configured.
=> Passive Email Threading

include/staff/helptopics.inc.php
Correct variable so that the last updated date and time shows correctly on `scp/helptopics.php`
=> 1.10 :: Fix Last Updated variable for Help Topics

include/client/tickets.inc.php
Remove extra `&nbsp;` which throw off the spacing
=> Cleanup Client Ticket Table

include/class.thread.php
The ThreadEntry::normalizeFileInfo() method is called from ::create(), but before the thread entry is saved. Therefore, the ::getThread() and ::getObject() methods may not return a valid object for posting the thread message.
References: #3029
=> thread: Fix crash processing problem attachments

include/class.task.php
Defer to agent's timezone on due date `datetime` selection instead of
defaulting to GMT.
* Includes commit dba6835 from PR #3430
=> Task Duedate Timezone 

bootstrap.php, include/class.osticket.php, include/class.validator.php, include/ost-sampleconfig.php, include/staff/header.inc.php, include/staff/syslogs.inc.php, include/staff/ticket-view.inc.php, main.inc.php, setup/test/tests/test.validation.php
Prior versions of osTicket blindly trusted http headers set by upstream proxies or agents. This pull request addresses possible remote XSS injection via X_FORWARDED_FOR header by introducing HTTP options to define a list of Trusted Proxies as well as address space of trusted Local Networks. CIDR notation (subnets) are supported.
**HTTP Option: TRUSTED_PROXIES (default: <none>**
To support running osTicket installation on a web servers that sit behind a load balancer, HTTP cache, or other intermediary (reverse) proxy; it's necessary to define trusted proxies to protect against forged http headers.
**HTTP Option: LOCAL_NETWORKS (default: 127.0.0.0/24)**
When running osTicket as part of a cluster it might become necessary to white list local/virtual networks that can bypass some …
=> XSS:  Validate HTTP_X_FORWARDED_FOR header.

include/ajax.forms.php
This addresses issue where list item abbrv. is not update because the update() method is
expects 'abbrev' key.
=> List Item Abbreviation

include/Spyc.php
Change to the Spyc library to correctly convert hex strings to INTs under PHP 7. Should fix issue #3620
=> Fixes issue #3620.

include/ajax.tasks.php, include/staff/templates/task-preview.tmpl.php
Fixes syntax error introduced with commit 71a6b2a0 & 6e0ddf2e
=> Syntax Errors Hotfix

include/class.format.php, include/class.forms.php, include/class.i18n.php, include/class.misc.php, include/class.timezone.php
Add timezone as a supported field. 
Possible use cases;
* Add timezone property to DateTime Field to specify the timezone for the time selection
* Specify timezone of `Schedules` (e.g Business Hours)
=> Add TimezoneField

include/class.thread.php, include/class.thread_actions.php, include/staff/templates/thread-entry-edit.tmpl.php
Store long thread entry body as an attachment if its length is more than max-length of a text field. 
This is necessary especially for emailed tickets which might contain excel document pasted into the body (inline attachment) of the email. We could increase the body field type to longtext - but that won't solve cases where the text is larger than the maximum packet size allowed by MySQL backend.
The technique implemented doesn't require any special flags - we simply set the entry body to `NULL` and the text is saved as an inline attachment for the entry. The attachment backends stores the file as it see fit - in the case of Database Backend, it already has a built-in chunking mechanism to go around max packet size allowed.
=> Chunk long text body

include/class.i18n.php
This addresses issues #1964 & #3668 where $cfg might be null and cause a
non-object error. Check if $cfg is set, if not, return the default en_US
language.
=> i18n: Fix getPrimaryLanguage() on non-object

include/class.dynamic_forms.php
This addresses issue where upon deletion of a form field and all its
entry values, the field record wouldn't be deleted from the `form_field`
table. This links another issue where you can't delete a list if its
been a field before, due to the list delete() function that checks for
list field records in the `form_field` table.
=> forms: Proper Field Deletion

include/class.thread_actions.php
This fixes an InconsistentModelException error when editing thread entries with inline images. The fix assumes that inline images are re-attached when a new ThreadEntry is created and the body is copied from the previous entry. Only the non-inline attachments need to be moved in the update query.
Fixes #3787
=> Fix crash editing thread entry with inline image

include/ajax.search.php
This addresses issue #3766 where javascript can be injected into the title of an advanced search.
=> Format the advanced search title so that it will not allow javascript

file.php, include/class.orm.php
This commit addresses an SQL injection vulnerability in ORM lookup function.
* ORM implementation failed to properly quote field names, used in SQL
statements, that might originate from unsanitized user input.
* AttachmentFile lookup allowed for key based SQL injection by blindly delegating non-string lookup to ORM.
=> CVE-2017-14396

include/ajax.users.php, include/staff/users.inc.php
This addresses issue #3815 where searching by User's phone number doesn't
work in v1.10. This adds phone number search capabilities for the User
Directory and User Search popup in v1.10.
=> oops: User Phone Search

include/class.task.php
This addresses an issue where updating a Task does not change the
`updated` column in the database. This adds a line to change the `update`
column when updating a Task.
=> tasks: Fix Task Updated Time

include/staff/templates/task-view.tmpl.php
This addresses issue #3782 where clicking Print on a Task gives you a blank
popup that hangs. This is because the Print button was being treated as a
Task action when it is actually not one. This adds a ternary operator to
give the proper Task actions the `task-action` class and gives the Print
button no class.
=> oops: Fix Task Print

include/class.cron.php, include/class.ostsession.php
This addresses an issue where expired sessions would not be removed from
the database. This caused the session table to fill up and create
unnecessary issues. This adds a cleanup method to remove all expired
sessions from the database when cron runs.
=> cron: Delete Expired Sessions

include/class.upgrader.php
This addresses an issue where the Upgrader will sometimes use an outdated
cached object and throw an error. This adds a the function to clear the
Model Cache every time the Upgrader runs an Upgrade Patch to get fresh
objects.
=> upgrader: Flush Cache On Upgrade

include/class.format.php
This addresses an issue where Outlook adds weird (and seemingly random)
_MailEndCompose tags to the email body which turns unwanted content into
links. This adds the _MailEndCompose tag to Format::sanitize() so it
will be removed from the email body.
=> issue: Outlook _MailEndCompose

include/class.file.php
This addresses the issue where files were being deleted before being sent
out in Agent responses. This was due to a bug in the query that gets the
orphaned files. This query was getting files created within the last 24
hours not after the last 24 hours. The query also had another bug that
would use the time from PHP instead of MySQL which could cause issues.
This updates the query as per @greezybacon's suggestions to delete
orphaned files that were created more than 24 hours ago.
=> issue: Files - deleteOrphans()

include/staff/system.inc.php
This addresses an issue on the forums where the query to determine the
size of the `file_chunk` table is making the page load really slow for
people with large tables. This updates the query to improve the
performance of the page load time.
=> issue: Information Page Performance

include/client/header.inc.php, include/staff/header.inc.php, include/staff/login.header.php, setup/inc/header.inc.php
This addresses a vulnerability where there was no `X-Frame-Options` header
which could potentially allow click jacking. This adds the
`X-Frame-Options: SAMEORIGIN` header so it will remove any chance of click
jacking. According to Mozilla Developer Docs:
```
SAMEORIGIN
The page can only be displayed in a frame on the same origin as the page
itself.
```
=> issue: Prevent Click Jacking

include/ajax.forms.php
This addresses an issue where you can exploit XSS in the help-topic AJAX
request. This adds a check for a refferal URL and if none it will return
a 403 Forbidden Response.
=> issue: AJAX Reflected XSS

include/class.misc.php
This addresses an issue where the `randNumber()` function would crash on
32-Bit systems if the ticket format was set to a really high amount of
digits (eg. ###################). This is because the `max()` value that
was being passed to `mt_rand()` exceeded the `mt_getrandmax()` limit which
caused an error. This updates the function to generate a random number for
each digit to avoid the `mt_getrandmax()` limit.
=> oops: Fix randNumber()

include/class.mailfetch.php
This addresses an issue where the 'DISABLE_AUTHENTICATOR' args were not
properly added to the `imap_open` params. This changes the `+=` operator
to `array_merge()` to successufully add the params.
=> issue: Fix imap_open Disable Authenticator

include/class.format.php
This addresses an issue where some Vimeo videos are not being sent in
Agent’s responses. This adds `player.vimeo` to the sanitize method’s
iframe section so that the iframe tag is not stripped.
=> format: Fix Vimeo iFrames

include/class.orm.php
In my further development of the ORM, I found this bug. It's a circular reference between the ModelInstanceManager and the QuerySet instances. It prevents the query statement and database resources from being cleaned up automatically when the query leaves scope (ie. function exits) and there are still records to be fetched from the database (for instance, if only the first record of a recordset with multiple rows was fetched).
This fixes an error where the ModelInstanceManager maintained a reference to the QuerySet instance, and the QuerySet instance managed a reference to the ModelInstanceManager instance (if it's the iterator for the query). Because of the circular reference, if the iterator is not exhausted, then the resource is not closed and the query remains open. This wastes memory …
=> orm: queryset: Fix circular reference error

profile.php
This addresses an issue where someone can "takeover" an account with only
a User's email and a User's previous ticket number. Once they get access
to a User's ticket they can go to the Ticket Owner's profile and change
the email to whatever they'd like. This adds a check on the profile to see
if the User is a Guest User. If they are a Guest then it kicks them back
to the ticket view. If they are the actual User it will let them view the
profile.
=> oops: Prevent Account Takeover

include/class.forms.php
This addresses an issue where the Help Text for Section Break fields does
not display custom Redactor styling correctly. Instead of displaying the
properly formatted Redactor content with it's styling it displays the
entire html for the Redactor content. This was due to the format method
used for the Section Break Field's Help Text. This updates the method from
`Format::htmlchars()` to `Format::display()` which displays the properly
formatted content. The content is also sanitized by `Format::sanitize()`
before saving to the database to avoid any chance of XSS.
=> issue: Section Break Hint

include/class.http.php
When opening attachments, we should only allow image files to be opened in the browser window. This prevents possible xss attacks where malicious code could be executed if an attachment were opened in the browser window. This was tested in Chrome, Safari, and Firefox.
=> Only allow image attachments to be opened in the browser window

include/class.ostsession.php
This addresses issue #4015 where osTicket’s cookies aren’t HttpOnly by
default. The HttpOnly flag helps prevent client scripts accessing the
cookie. This updates the method that sets the cookie params to include
the HttpOnly flag.
=> issue: Httponly Cookies

include/ajax.forms.php, include/class.forms.php
This addresses an issue where someone can bypass the file restrictions on
the file upload field in the Client Portal. This adds the allowed
extensions and file types to the field options so that User’s cannot
upload anything other than the allowed file types.
=> issue: File Upload Bypass

include/staff/system.inc.php
This addresses issue #4325 where the Language Pack Locales are mismatched.
The Locale for the first language is displayed on the second language,
etc. This updates the `$manifest` variable to be set before we display
data so the correct `MANIFEST` file is included and all language data is
displayed correctly.
=> issue: Language Pack Locale Mismatch

include/cli/modules/unpack.php
This addresses issue #4322 where deploying via CLI is missing
`bootstrap.php`. This is due to the `get_include_dir()` function that
tries to include a file from the destination which doesn’t exist yet,
causing a fatal error. This updates the function to use `$this->source`
instead of `$this->destination` to correctly find and include
`bootstrap.php`.
=> issue: CLI Deploy Missing Bootstrap

include/class.user.php
This addresses issue #4329 where you can import a User with no email
address via CSV file. Once the User is added and you try to update them
with an email address it fails due to no default email. This updates the
check for email address from `!isset()` to `empty()` which will correctly
check for empty string.
=> issue: User Import No Email

include/class.config.php, scp/tickets.php
This addresses an issue where disabling Ticket Locks but setting a time
for the Lock Timeout will always throw a "lock required" error. This adds
a check to see if locks are enabled AND there is a time set. If locks are
disabled it will not throw the error.
=> issue: Ticket Lock On Disable

include/class.thread.php
This addresses an issue on the Forums where the Auto-Assignment Thread
Event (configurable via Help Topic) uses the Email of the User rather than
the User’s Name. This adds the correct function to retrieve the User’s
Name if the User has an Account.
=> issue: Auto-Assignment Log

include/class.config.php, include/class.dept.php, include/class.format.php, include/class.thread.php, include/staff/department.inc.php, include/staff/helptopic.inc.php, include/staff/tickets.inc.php, scp/forms.php
It may be possible to steal or manipulate customer session and cookies, which might be used to impersonate a legitimate user, allowing the hacker to view or alter user records, and to perform transactions as that user. Sanitation of hazardous characters was not performed correctly on user
input.
osTicket did not properly sanitize array values in `Format::htmlchars()`. Some values in the Admin Interface were not properly sanitized and returned to the response.
=> Address Security Issues On #4331

scp/js/scp.js
This feature adds the ability to search for the _canned response_ by title in the post reply form.
=> Feature: canned response rendered using select2

include/ajax.orgs.php, include/ajax.tickets.php, include/ajax.users.php
This addresses issue #2655:
some research (e.g. searching for 3 or more whitespaces) raise the error `Unknown column '__relevance__' in 'order clause'`
=> Issue: SQL Error Unknown column '__relevance__' in 'order clause'

include/class.thread.php
This addresses an issue introduced with a3d896c where TextThreadEntryBodies
are not keeping their new line characters causing the email format to appear
wonky. This balances the entry and then htmlchars it to ensure no XSS.
=> issue: TextThreadEntryBody Sanitize

setup/inc/footer.inc.php
This addresses issue #4339 where the installer footer references the wrong
copyright date.
=> issue: Installer Footer Copyright

include/class.file.php
An index was added to the v1.11 branch to support the ORM query. Because the index cannot be applied to v1.10, the query was rewritten for the 1.10.x branch to provide better performance without changes to the database. When 1.10.x was merged into 1.11.x the rewritten SQL accidentally showed up. This reverts that merge to use the original ORM query.
=> Revert "issue: Orphaned File Query Rewrite"

include/client/tickets.inc.php
This addresses an issue where client side column sorting does not work at all. This is due to the if/else statement that checks for a REQUEST sort order and if the REQUEST sort order matches an `$orderWays` array value. The if statement returns TRUE for DESC and sets the sort order to DESC as it equals '-' (a dash) but ASC equals '' (an empty string) so it returns FALSE which fails-over to the else statement setting the sort order to DESC. In addition, this adds sorting icons the the column headers to make it more obvious they are sortable.
=> issue: Client Side Column Sorting

include/class.forms.php
This addresses an issue on the forums where osTicket does not add the proper values to any custom choices field template variable. This adds an `asVar()` function to `class ChoiceField` so we can return the proper values for the template variables.
=> issue: ChoiceField Template Variable

include/cli/modules/unpack.php
This addresses an issue introduced with #4332 where the deploy CLI breaks upon deploying to an existing location. This checks to see if there is a bootstrap file in the destination first and if so it uses that one if not uses the source.
=> issue: CLI Deploy Missing Bootstrap Fix

include/class.mailer.php
This address issue #4366 where sending a User a password reset email throws a fatal error of "object of type EmailAddress cannot be used as an array". This adds a switch case for EmailAddress to get the User's email address as a string not an object.
=> mailer: EmailAddress Object as Array

include/class.ticket.php
This addresses issue #4370 where Users responding to tickets via Client Portal triggers a “Failed to add recipient: @localhost” Mailer Error in the osTicket Logs. This is due to the `notifyCollaborators()` function that lacks a check for an empty mailing list.
=> collab: @localhost Mailer Error

scp/js/scp.js
This addresses issue #4372 where any Redactor text box within jQuery sortable is not clickable. This is due to Redactor not being an actual input field, rather a div, so sortable doesn’t see it as an input.
=> issue: jQuery Sortable Redactor

include/client/templates/thread-entries.tmpl.php
This addresses an issue where the client side thread entries are all grouped within the same div. This pushes all grouped entries to one side of the page making them illegible.
=> issue: Client Side Thread Entries

js/redactor-osticket.js
This commit makes sure that when the Reset button is hit, we only reset File Upload Field attachments for the specific form we're on.
Ex: Viewing a Ticket as an Agent and switching between 'Post Reply' and 'Post Internal Note' tabs. If you had an image in the Post Reply file upload field but switched to the Post Internal Note tab and hit Reset, only the text/attachments on the Post Internal Note tab would be cleared.
(Improves upon #4369)
=> Reset Button Fix:

scp/js/scp.js
This address an issue introduced with #4311 where selecting a canned response does not insert it at last cursor position, rather at the top of the text box.
=> issue: Redactor Select2 Cursor Position

include/class.forms.php
This addresses an issue with PriorityField Template Variables introduced with #4359 where the priority variable will appear as "Array" instead of the actual value. This adds an `asVar()` function to `class PriorityField` to get the appropriate data.
=> issue: Priority Field Template Variable

include/class.thread.php
This addresses an issue where deleting a field and all it's data will delete the form field record in the database causing all events containing the field to crash the ticket page.
=> issue: Deleted Field Thread Events

include/class.mailer.php
This commit addresses an issue where email alerts were not being properly sent out if the name format is set as 'Last, First' or if it has special characters. We now encode names with quotation marks to ensure that emails are sent out properly (escape possible commas).
=> Email Name Format:

include/class.config.php, include/class.ticket.php, include/i18n/en_US/config.yaml, include/i18n/en_US/help/tips/settings.ticket.yaml, include/staff/settings-tickets.inc.php, include/staff/ticket-edit.inc.php
This commit adds an Admin setting that requires a Ticket to have a Help Topic before it can be closed. It can be set by going to:
Admin Panel | Settings | Tickets | Require Help Topic to Close
If enabled, Tickets will have a warning banner across the bottom of the page, a warning banner when trying to change the Ticket status to Closed, and a warning flag beside the field when editing the Ticket.
By default, this setting is NOT enabled.
=> Setting - Require Help Topic to Close:

include/class.forms.php
This addresses issue #4155 where editing a ticket using a different session causes custom file uploads to drop from the ticket.
=> issue: Custom File Upload Dropping

include/class.queue.php
This addresses an issue where class Queue sets SavedSearches flags to `FLAG_QUEUE` causing the SavedSearches to become Primary Queues.
=> issue: Saved Searches Flags

scp/css/scp.css
This addresses an issue where Select2 Placeholders are being cutoff due to a bug in Select2.
=> issue: Select2 Placeholder Bug

scp/js/scp.js
This addresses an issue where Microsoft IE 11 apparently does not like `event.target` syntax in javascript and breaks the Canned Response Select2.
=> issue: IE Select2 Target

include/staff/ticket-edit.inc.php
This commit addresses an issue where the validation error for trying to save a Ticket without a Help Topic was not being shown as a result of the error message that was added to ensure that the Help Topic selected is Active.
=> Help Topic Required Error Message:

include/ajax.search.php, include/class.list.php, include/class.queue.php, include/class.search.php, include/staff/queue.inc.php, include/staff/templates/queue-column.tmpl.php, include/staff/templates/queue-columns.tmpl.php, include/staff/templates/queue-navigation.tmpl.php, include/staff/templates/queue-savedsearches-nav.tmpl.php, include/staff/templates/queue-subnavigation.tmpl.php, scp/tickets.php
So I'm abandoning my previous pull request in favor of a new one. Since custom queues are making their official debut in v1.11 (yay!), I've taken the liberty to start finding the differences between my branch and the upstream branch. This pull request is the start of the conversation to tie up all the loose ends and merge the two ideas.
I think I've got most everything. A couple of the commits showed differences, but the merge conflicts were too extreme for me to figure out. I'll try another couple approaches to make sure we've got everything, but I think this is the most of it.
The only major enhancement here is the concept of creating team-based queues, where the members of a team can share a common queue. 
This also includes a database usage fix to reduce the queries needed to render …
=> Custom Queues Merged for 1.11

scp/tickets.php
This commit addresses an issue where the Agent could set a Default Ticket Queue in their profile, but the System Default queue would be shown instead.
=> Agent Default Queue:

include/class.ticket.php
This addresses an issue introduced with `510046c5` where tickets with no Help Topic can not be reopened. This is due to a check on `isReopenable()` where it returns `null` instead of `true` if there is no help topic; therefore returning false and not allowing the ticket to be reopened.
=> status: Allow Reopen

scp/css/scp.css
This adds an enhancement to the Canned Response Select2 showing more options within the list. The length is automatic and is based on how many Canned Responses you have Enabled.
Limits:
- Height maxes out at 400px so it doesn’t run off the screen
=> canned: Canned Response Select2 Height

include/staff/templates/thread-event.tmpl.php
This addresses an issue introduced with `9ab2317` where the icon for the event still shows even though we continued and didn’t return the event description.
=> issue: Deleted Field Thread Events (template)

include/class.thread.php
This commit fixes an issue where referrals were being considered successfully saved even if that referral already existed, resulting in multiple thread events for the same referral.
Instead, if we find that the thread is already referred to the referee, refer should return false so that an error message is displayed stating that we were unable to refer the ticket.
=> Referral Assignment Issue:

include/client/templates/sidebar.tmpl.php
This addresses an issue where the client portal shows Featured FAQs on the sidebar even though the Knowledgebase is Disabled.
=> issue: Featured FAQs On Disable

include/class.queue.php, include/class.search.php
If an Agent has the Miscellaneous setting checked to see all Tickets in search results, they should be able to see the search results of Tickets regardless of their access or if the search is saved or not. They should NOT, however, be able to view those Tickets.
This setting is set here:
Admin Panel | Agents | Choose an Agent | Permissions tab | Miscellaneous tab | Search (checkbox)
=> Search All Tickets Setting

include/upgrader/streams/core/934b8db8-ad9d0a5f.task.php
Retain old search criteria when isolate fails. This provide for ability to fix issues with isolation post-upgrade.
=> Upgrader: Old search criteria

include/staff/ticket-tasks.inc.php
This addresses an issue where it appeared as though tasks could not be assigned to teams if an agent in the team was not a part of the task's department. The assigment was actually taking place, however, it was not showing up in the Assignee column. Now the form will correctly display the column
=> Task Assigned Team Issue:

scp/canned.php, scp/faq.php
This addresses an issue where FAQ & Canned Response attachments are dropping when another agent edits the FAQ or Canned Response.
=> issue: FAQ & Canned Attachments Dropping

include/class.attachment.php
This addresses an issue where uploading a file you’ve uploaded before but renamed is not saving the new name in the Attachment table.
=> issue: Old Attachment Names

include/class.forms.php
This addresses an issue where FileUploadFields are displaying the old names of existing files with new names.
=> issue: Wrong Attachment Names

include/class.filter.php
This addresses an issue reported on the forums where the ticket filter Rule option of "Does Not Match Regex" isn’t working properly; instead it works in reverse.
=> issue: Ticket Filter Does Not Match Regex

setup/test/tests/test.git-conflicts.php
This adds a test for Git Conflict Markers to prevent committing unfinished
merge conflicts. This will find any `<<<<<<< HEAD`/`>>>>>>>` markers
and will fail out with the line of code, filename and line number.
=> tests: Git Conflict Markers

include/class.queue.php
This addresses an issue where row conditions are working in the preview but not in the actual ticket queue. This updates the `getQueue()` function to lookup the CustomQueue by `queue_id` if there is no CustomQueue object found in the QueueColumn.
=> queues: Row Conditions

include/class.format.php
This commit removes the logic that was used for time within 2 days which would give a result of either today or tomorrow when something could actually be in 2 days instead.
It also rounds relative time that is within 29 days so that the result will be more accurate.
Ex: 1.99 will round to 2 instead of showing 1
=> Relative Time Fixes:

include/class.queue.php
This addresses an issue where Column Conditions are not overwriting the Row Conditions. This changes the order of `array_merge()` to make Column Conditions overwrite the Row Conditions.
=> queues: Column Conditions Overwrite

include/class.auth.php, include/class.client.php, include/class.staff.php, include/class.user.php
This adds a Signal to clean Agent and User sessions upon setting/resetting their password. If an Agent/User resets their own password and has multiple sessions open it will log them out of every session except the one they’re on.
=> sessions: Clear On Password Set/Reset

include/staff/tasks.inc.php
This addresses an issue where searching for a Task by title returns all Tasks in the search. This is due to the visibility filtering methods used to filter tickets by staff's visibility.
=> issue: Task Term Search

include/class.dynamic_forms.php
This addresses an issue where creating an advanced search with selection field "does not have a value" throws a fatal error. This was due to an improperly named search method "notset".
=> issue: SelectionField nset

include/class.pdf.php
This addresses an issue where `SetAutoFont()` was making the Thai PDFs break. This adds the `AUTOFONT_RTL` flag to only autodetect RTL languages and nothing else.
=> issue: mPDF SetAutoFont RTL

include/class.dynamic_forms.php
This addresses issue #4470 where Users creating tickets via Client Portal and failing to fill out a required field makes disabled fields by Help Topic appear on the page. When the disabled fields appear they allow Users to populate and save data that they were not meant to submit.
=> forms: Disabled By Help Topic Users

include/staff/users.inc.php
This addresses an issue where people who do not have a phone field on the contact information form go to search for a User in the User Directory and the system crashes. This is due to the search query that always contains the phone field variable. This only adds the phone variable to the search query if the field actually exists.
=> issue: CDATA Phone Contains

include/class.format.php
This addresses an issue where images in email signatures containing a `data-cid` attribute will either crash the ticket page or not show the image in the signature in IE.
=> issue: Image CID Attributes

include/class.filter.php, include/class.filter_action.php
This commit fixes the way we validate filter actions before saving a filter. Now, the code will accurately validate the action without needing a filter_id first while also making sure all validations stay within the validate_actions function.
=> Filter Action Saving Fix:

include/class.staff.php
This commit fixes an issue where the ORM was trying to get invalid Staff fields (which are actually keys  in the config table), therefore throwing an error.
=> Staff Profile Updates:

include/class.charset.php
This will be useful when converting content on the fly on write or read -allowing for support for output filter for file storage backend.
=> Charset: Add generic transcode php_user_filter

include/class.filter_action.php
This commit fixes an issue we had with adding a Filter Action to Send an Email. We had an option at the top for 'Default System Email', however, it did not have the Email ID or address for the system email and would throw an error if chosen. Now, we just retrieve the emails with their IDs and values with the Default System Email being the initial value selected in the list of options.
=> Filter Action Send an Email Issue

include/class.collaborator.php, include/class.user.php
This commit further corrects issues where emails were being sent out with names being improperly formatted if the name format is set as 'Last, First' or if it has special characters.
=> Email Name Format

include/class.dynamic_forms.php
This addresses an issue introduced with #4124 where searching for a Selection Field with the criteria "does not have a value" throws an `implode()` warning.
=> oops: Selection Search Bug

include/client/open.inc.php
This addresses issue #4473 where users creating a ticket with the Help Topic preselected shows a validation error for the Issue Summary field. This is due to the new `getFormName()` function that creates new field form names based on the user’s/agent’s session. When the Help Topic is preselected, `_form` is not set for each field so the hashed name of the fields before ticket submit is different than after ticket submit.
=> issue: Default Help Topic Issue Summary

include/class.ticket.php
This commit fixes an issue where we were not emailing attachments for initial responses when creating a Ticket.
=> Creating Tickets with Attachments

account.php
This addresses an issue where registering as a non-existing user fails to register nor create an account. This is due to a check added in `824e92` that fails if there is no User model found for the address provided.
=> issue: Existing User Registration

scp/queues.php
This addresses an issue where newly added queues in the Admin Panel do not show up in the list of queues nor in the ticket view. This is due to the function that does not set any additional flags on queues if one already exists.
=> issue: Newly Added Queues

scp/forms.php
This addresses issue #4493 where the system renders form instructions as plain text instead of HTML. The data is saved in the db as encoded HTML and upon pulling the data we do not decode it back to HTML for rendering.
=> forms: Render Instructions

js/osticket.js, scp/js/scp.js
This addresses an issue where clicking Open, Post Reply, etc. more than once whilst creating/responding to a ticket will generate duplicate requests. This causes duplicate responses to be sent out or duplicate tickets being created. This adds jQuery, on both Agent and User side, to disable the submit buttons when the "Loading" popup appears so you cannot click the button more than once.
=> issue: Duplicate Page Requests

include/class.forms.php, include/class.thread_actions.php, include/staff/ticket-open.inc.php
This addresses an issue where `$_SESSION[':form-data']` files are not including the new filenames.
=> issue: Session form-data Files

include/class.queue.php
This commit fixes an issue we had where the bolding on the Ticket Number and Subject columns of advanced searches showed the opposite of what they should have. We instead want them to be bold if the Tickets are Unanswered.
=> Advanced Search Column Conditions

include/i18n/en_US/templates/ticket/upgraded.yaml, include/upgrader/done.inc.php
fixes two urls in the code to point from the old /wiki to the same place in the new doc.osticket.com
=> change old wiki urls to new doc urls

include/class.filter.php
- Let validate_actions pass if we are trying to disable/archive a Help Topic so that the filter flag can be set.
- Make sure we do not throw validation errors when deleting a filter action. Just delete it.
=> Filter Action Validation Fixes

include/class.ticket.php
This commit ensures that we will always have the correct display of values for the Ticket Source regardless of if the key and value differ.
Ex: if we had a Ticket Source that contained a space in the value, the key would be camel cased in the database enum for source
=> Ticket Sources

scp/tickets.php
When clicking 'All Tickets' for a User from within a Ticket, make sure we search using the User's email address instead of their Full Name in case we have users with the same name.
=> View All Tickets for User

include/ajax.tasks.php, include/ajax.tickets.php, include/class.attachment.php, include/class.forms.php, include/class.thread.php, include/class.thread_actions.php, include/staff/ticket-open.inc.php, scp/tasks.php, scp/tickets.php
- Make sure we keep attachments in the session even if the page refreshes to display an error message
- Reverse the array of files to be id => name instead of name => id
- Make sure we retain the old ticket or task id if we encounter an error while trying to create a ticket or task from a thread entry
- Make sure we have a valid fileId before returning file info
- Make sure we can still add files for Canned Responses (id and name flip issue)
- Make sure we can still add attachments to Internal Notes for Tickets and Tasks
=> Form Attachment Issues

file.php, include/ajax.tasks.php, include/ajax.tickets.php, include/class.attachment.php, include/class.canned.php, include/class.file.php, include/class.forms.php, include/class.thread.php, include/class.ticket.php, open.php, scp/tasks.php, scp/tickets.php, tickets.php
This commit ensures that we will always get the correct attachment name regardless of if the file content is the same. Additionally, it ensures that the file_ids for attachments are compared in the correct order (elseifs)
=> Attachment Names Issue

include/ajax.search.php, include/class.format.php, include/class.forms.php, include/class.list.php, include/class.queue.php, include/class.search.php, include/class.ticket.php
This commit addresses longstanding memory and speed issues with tickets export especially when exporting large set of tickets.
The implementation borrows heavily on Custom Columns feature, which introduced the idea of using placeholder field to parse the data from query (db) instead of making models to do the hard work which led to related models getting fetched too -- and hence the memory issues.
The commit also addresses caching of choices for selection fields and such to avoid expensive trips to database for each row!
Todo:
=> Export: Make Export Fast Again

include/class.export.php, include/class.queue.php
This addresses an issue where export does not work due to a fatal error "Unknown column 'R0.state' in 'where clause'". This was caused by #4558 due to the removal of enums and the `state` column. This updates the filter to match the `event_id` instead of `state`.
=> issue: Export Event State Error

include/class.user.php
This addresses an issue reported on the forum where deleting a User will throw a fatal error. This was caused by #4558 where the `state` column was mistakenly overwritten with `event_id`. In addition, this changes `$deleted` to `$status_id` for better readability.
=> issue: Delete User Error

include/class.config.php, include/cli/modules/upgrade.php
This patch fixes the issue where the configuration was not properly reloaded during an upgrade. The configuration items were stashed in the Config class and were not re-fetched from the ::load() method. Additionally, this patch forces the ORM cached objects to be flushed on each loop through the automated upgrader to ensure that cached data which might have been modified directly in the database during the database process is destroyed.
=> upgrade: Actually re-fetch the config from database

js/osticket.js, scp/js/scp.js
This addresses an issue with pull #4472 where disabling the Submit button does not submit the Input value for the button. This affects the installation of plugins, where the Install Path is not sent therefore the plugin is not installed. This clones the original submit button, hides it, then displays a dummy disabled Submit button which will submit the value and prevent dupe posts.
=> issue: Dupe Page Requests Fix

include/class.report.php
This commit fixes an issue where we were not able to see all of the departments, topics, and agents that should have been included in the report. The logic for the  GROUP BY in the queries was changed, so we just manually added them back in.
=> Dashboard Statistics Issue

include/class.client.php
This addresses an issue where replying to a ticket causes a Fatal Error for the system. This is due to the `$ticket` object not being set before the else statement therefore causing the `getId()` function to fail. This breaks down the if/else statement to make sure the `$ticket` object is in-fact set before continuing.
=> issue: ticket_link Fatal Error

include/i18n/en_US/queue.yaml
This addresses an issue where poor little `sort_id` was sadly forgotten for the two main-level queues "Open" and "My Tickets".
=> issue: Queue sort_id

include/class.queue.php, include/class.search.php, include/i18n/en_US/queue_column.yaml
This commit addresses where wrong "primary" field was used to indicate Ticket Status column. It also fixes an issue where sorting was done via `id` instead of `name`.
=> Status Column: Fix display and sorting

include/class.forms.php
This commits adds a flag to skip validation on $field->getClean() routine, it is necessary to allow FileUploadField to fetch "injected" files.
=> FileUploadField Validation

include/ajax.search.php, include/class.config.php, include/class.format.php, include/i18n/en_US/config.yaml, include/i18n/en_US/help/tips/settings.ticket.yaml, include/staff/settings-tickets.inc.php, include/staff/templates/queue-navigation.tmpl.php, scp/js/scp.js
This adds a setting in the Ticket Settings to give the option of showing the ticket counts on Top-Level queues. If enabled, this will populate the ticket counts next to the Top-Level queue names like they used to be. The only caveat is the counts are triggered by mousing-over any of the queue names as we only load the counts when we need to display the sub-queues (for better performance).
This also adds a new format function called `number` (Phase 1). As of now it will format any integer to a comma separated number (eg. `1337 -> 1,337`).
=> queue: Top-Level Ticket Counts

scp/queues.php, scp/tickets.php
This commit fixes an issue where Agents were able to delete their default queue which then prevented them from going to any queue upon logging in. Now, they will see an error message if they try to do so.
=> Deleting the Default Queue

include/class.format.php
This addresses an issue where the create_date variable is showing as Unix timestamp instead of formatted date. This was due to a typo introduced in commit `8623ed6` where the `$format` argument was forgotten for `Format::datetime()` in the `FormattedLocalDate::getVar()` method.
=> issue: create_date Variable

include/staff/department.inc.php, include/staff/departments.inc.php, scp/departments.php
This addresses an issue where configuring a System Email to have a Department and then editing/saving changes on the configured Department will change the System Email's Department back to the the default Department. This was due to a un-needed Department Status check introduced with commit `1d361b5`. This also updates all instances of Dept Status comparison to be case insensitive and non-translated.
=> issue: Email Default Dept

include/class.faq.php, include/class.page.php
This addresses an issue where inserting images on a Page or FAQ and having the setting enabled for "Login required to view attachments." does not display the images at all when the Page/FAQ renders in view. This is due to the Page/FAQ update functions that were not updated to fit the new `id=>name` format for `keepOnlyFileIds()` introduced with `f179cf1`.
=> issue: FAQ/Page Attachments

include/class.client.php
This addresses an issue where Users updating their profile will throw an SQL error in the system logs. This is due to a line of code trying to set a value for the `dst` column which no longer exists as of `1.10.0`.
=> oops: Remove DST From User Update

include/staff/ticket-view.inc.php
This addresses an issue where Department Managers would not see the option for Marking tickets as (un)answered due to an elseif (should be an if instead).
=> issue: markAs() elseif

include/ajax.tickets.php
This addresses a typo in the `markAs()` function in `ajax.tickets.php`. DOH! Should’ve ran the lint tests
=> oops: markAs() Typo

include/staff/templates/user-import.tmpl.php
This commit updates the instructions for User imports letting the Agent know they should type 'Name, Email' on the first line and then put each new User Name/Email on the following lines to import Users.
=> Clarify User Import Instructions

include/staff/dashboard.inc.php
This addresses an issue where exporting statistics via the dashboard within a certain timeframe (eg. 07/01/2018 -> One Quarter) will always export the statistics from the selected date up to today. This is due to the Period option always being set to "Up to today" when the Export button is clicked which in return exports the stats from the selected start date to today. This adds JS to set the period the Agent selects so the Export will return the stats from the selected date to the selected period.
=> issue: Dashboard Export Period

include/staff/templates/task-view.tmpl.php
This addresses an issue where the Loading overlay on Tasks will not disappear after the request was submitted. This adds two lines to first hide the "Loading" modal and then toggle the overlay.
=> issue: Hide Task Loading Overlay

include/staff/templates/task-view.tmpl.php, include/staff/templates/tasks-actions.tmpl.php, include/staff/ticket-tasks.inc.php
This commit addresses issues we had with viewing Task(s) within a Ticket:
1. When viewing the table of all Tasks on a Ticket, the Options dropdown should only allow the Agent to Reopen or Close the Tasks based on the status of the Tasks.
Ex: If there is only 1 Open Task, you should only see the 'Close' Option
If there are 2 Closed Tasks, you should only see the 'Reopen' Option
If there are multiple Tasks in which some are Open and some are Closed, you should see both the 'Reopen' and 'Close' options
2. When viewing an individual Task within a Ticket, the status options were the opposite of what they should have been. Now, if the Task is Open, the Agent will see the option to 'Close' the Task. If the Task is Closed, the Agent will see the option to 'Reopen' the Task.
=> Issue: Tasks Within Tickets

include/staff/templates/collaborators.tmpl.php, include/staff/templates/task-view.tmpl.php
This commit changes the wording for Collaborators on Tasks to match the wording for Collaborators on Tickets.
=> Task Collaborators

include/staff/templates/queue-quickfilter.tmpl.php
This addresses an issue where having more than 30+ choices for a Quickfilter makes the dropdown run off the page causing some choices to be hidden. This makes it to where if you have more than 20+ choices we will make the dropdown a fixed height and make it scrollable.
=> issue: Scrollable Quickfilters

include/class.task.php, include/class.thread.php, include/class.util.php
This addresses a fatal error when adding a new response to a Task with Collaborators. When we implemented the MailingList for Users/Collaborators we forgot about the little Task Collaborators (poor little guys). This adds a new function called `getRecipients()` to `class Thread` that utilizes MailingList instead of UserList. This also adds two new functions to `class Util` that retrieves the User’s `user_id`.
=> issue: Task Response With Collaborators

include/class.forms.php
This commit fixes an issue where a Short Answer Field would show as Empty if the value saved in it was '0'
=> Issue: Can’t use “0” in Short Answer Field

include/class.staff.php, include/staff/profile.inc.php, scp/tickets.php
This pull adds a Profile Setting for Agents to choose where to redirect after replying to ticket. The two options are Queue (redirect to queue to work on other tickets) or Ticket (redirect back to same ticket to continue working) with the latter being the default. The setting is configurable for each Agent in the helpdesk.
=> profile: Reply Redirect

include/staff/login.tpl.php
This updates the references to the old jQuery UI filename to the new filename. (this needs #4672 merged first)
=> jq: Update jQuery UI References

include/staff/templates/refer.tmpl.php
This addresses an issue where removing a Referral from the Manage Referrals modal just loads and loads, never actually removing the referral. This is due to the AJAX URL containing an extra `/` causing an "Unsupported URL" error.
=> issue: Remove Referral Borked

include/staff/templates/queue-subnavigation.tmpl.php
This addresses an issue where adding SubQueues hides PersonalQueues. This was due to the variable `$childs` being reset in the sub-navigation template.
=> issue: SubQueues Hide PersonalQueues

include/ajax.tickets.php
This commit addresses an issue where a Department might have the Ticket Assignment option set to All Agents, but when trying to mass assign Tickets, only Department Agents were shown in the list.
Note: If mass assign is done on Tickets with different Departments that have different Ticket Assignment rules, Tickets will only be assigned to the Tickets that are allowed the assignment.
=> Issue: Mass Assign

include/class.api.php, include/class.banlist.php, include/class.dynamic_forms.php, include/class.filter.php, include/class.filter_action.php, include/class.forms.php, include/class.ostsession.php, include/class.queue.php, include/class.search.php, include/client/edit.inc.php, include/client/open.inc.php, include/client/profile.inc.php, include/client/register.inc.php, include/staff/filter.inc.php, include/staff/templates/org-lookup.tmpl.php, include/staff/templates/user-lookup.tmpl.php, include/staff/ticket-edit.inc.php, scp/filters.php, setup/test/tests/class.test.php
This is an effort to fix all the warnings and crashes running osTicket on PHP 7.1
=> 1.11 Should Support PHP 7.1

scp/css/scp.css
This addresses an issue where the second row of translation flags are not clickable when editing a Form with 23+ languages installed. This adds a `height` of "auto" so that the entire div fits the flags’ surface area, making them clickable again.
=> issue: Translation Flags Not Clickable

include/cli/modules/i18n.php
Crowdin requires a `branch` argument when requesting the language pack download from their system.
=> i18n: Fix build language packs for the 1.10.x branch

include/class.banlist.php, include/class.filter.php
This addresses an issue where the system banlist throws the error "SYSTEM BAN LIST filter is DISABLED". This is due to the Filters moving to ORM but not updating everywhere they are used.
=> issue: System Ban List

js/filedrop.field.js, scp/js/scp.js
This fixes an issue introduced in the upgrade to jQuery three. The filedrop field was not updated correctly and drag and drop files was broken. 
Additionally, this handles cases where files are dragged over the box but not dropped. The style of the box is correctly reset after the drag leaves the box.
=> filedrop: Fix file drag and drop

scp/plugins.php
This addresses issue #4718 where deleting a plugin using PHP 7.2 throws an error. This is due to errors not being passed to uninstall which causes the "Too Few Arguments" error.
=> issue: PHP 7.2 Plugin Delete

scp/tickets.php
This addresses an issue where main queues were not marked as active resulting in "New Ticket" link getting auto-set as active (bold).
=> Selected Navigation Item

avatar.php, include/class.avatar.php
This addresses issue #4700 where local avatars where breaking queues with Avatar Annotation. This is due to the local avatars not having a `setSize()` function. This updates local avatars so that they can be resized.
=> issue: Local Avatar Annotation

include/upgrader/prereq.inc.php
This addresses issue #4738 where the Upgrade and Migration Guide link is incorrect. This updates the link to the new Documentation site.
=> issue: Upgrader Wrong Guide Link

include/ajax.users.php, scp/js/scp.js
The CDATA table may be dropped on upgrade and is not created on new installs. So it should be created on demand when searching for users.
Also, fix a Javascript issue not highlighting tabs in red where errors exist.
=> users: Fix searching of users

scp/js/scp.js
This addresses issue #4725 where there is no save button when editing a quick note. This is due to the jQuery update which changed how a few things work with redactor.
=> issue: No Save Button On Quicknotes

include/class.forms.php
This commit fixes an issue where we failed to upload attachments on Information Fields. In the to_config function, we were only taking the array_values of attachments which would return an array with only the file name ([0] => 'filename') instead of an array with the file id and file name ([123] => 'filename').
Now, when we pass the keepers to keepOnlyFileIds, we have a file id that can be passed to the upload function.
=> Issue: Attachments on Information Fields

include/class.organization.php
This addresses issue #4579 where setting a Custom Column to User Organization and choosing the User Org Link filter the system shows the wrong link to the Org. This is due to "scp/" not being added to the URL therefore showing an invalid link.
=> issue: Custom Column Org Link

include/class.ticket.php
This addresses issue #4743 where the system ignores Internal Notes on Ticket Creation. This is due to the ticket being assigned and not having the Internal Note passed along.
=> issue: Internal Note Ignored

include/ajax.forms.php
This addresses issue #4716 where updating a Ticket Status throws a fatal error of "Too few arguments" when using PHP 7.2. This is due to `$errors` not being passed to the `update()` function causing PHP 7.2 to freak out. This creates an `$errors` array and passes it to `update()` so PHP 7.2 is happy and we are all happy. :)
=> issue: PHP 7.2 Ticket Status

include/ajax.tickets.php
This addresses issue #4756 where the `%{recipient.ticket_link}` variable is not being replaced when the canned response is loaded in the reply box; all other link variables work. This is due to the recipient object not being passed to the variableReplacer which means the ticket_link is not available. This adds the recipient object to the variableReplacer so the ticket_link variable is properly replaced like the others on load.
=> issue: Canned Response Variables

include/client/knowledgebase.inc.php
This addresses an issue reported on the forum where searching for a keyword in FAQ search brings back more results than it should. This is due to the format of the query selecting the results, essentially, the `WHERE NOT` statement is not properly formatted so the `OR` statements take precedence over the `WHERE NOT` causing non-public results to be shown to the client. The `WHERE NOT` statement contains the bit to select from only public faqs and since the `OR` takes precedence it will return the non-public results too.
=> issue: FAQ Search Results

include/staff/faq.inc.php, scp/faq.php
This addresses an issue reported on the Forum where creating a new FAQ and not filling out required information returns the correct error but returns the incorrect template (FAQ View Template). This is due to the check for an FAQ when determining the template to return. This adds a check for the FAQ ID to determine if it’s an actual FAQ or just a model instance.
=> issue: FAQ Return Errors

include/class.pdf.php, include/mpdf/vendor/mpdf/mpdf/src/Config/ConfigVariables.php
This commit fixes 2 issues we had with using MPDF to export Tickets:
1. Tickets with inline images
To refer to images as var:varname, imageVars needs to be set for the MPDF object.
2. Tickets with tables
When exporting a Ticket where a Thread Entry contains a table, we must ignore table percents and table widths, otherwise, it will always throw the error "Word is too long to fit in table"
=> Issue: PDF printout

include/client/view.inc.php
This addresses an issue mentioned in the forum where having more than one custom field on a ticket shows the same title for all forms on the client-side ticket view (after creation). This adds an array of the form names indexed by sort order and displays them in the correct order with the correct names.
=> issue: Duplicate Form Titles

include/class.queue.php, include/staff/templates/queue-columns.tmpl.php
Allow admin to setup columns when creating a new parent queue and address an issue where Assignee standard columns used a wrong Id.
=> Queue Columns

include/staff/orgs.inc.php
This addresses issue #4803 where sorting by Users on Organizations does not sort properly. It sorts by name instead of the User count. This corrects the value in the `$sortOptions` array from `users` to `user_count`.
=> issue: Organizations Users Sort

include/class.pdf.php
This addresses an issue where clicking print on a Task throws a fatal error. This is due to the Task2PDF function passing a string instead of an array to `Mpdf::__construct()`. The `__construct()` of class Mpdf requires an array of configurations so we are now passing an array instead of a string.
=> issue: Task Print PDF

include/staff/category.inc.php
This addresses issue #4810 where having more than one language installed and trying to add a new FAQ Category with a Parent Category relation fails to add the Parent Category relation. This is due to multiple Select2 fields; the POST data includes only the last Select2 field's value instead of the one in the tab you're currently on. This adds a script to set all Select2 fields in all the available languages to the same value so the POST will always contain the appropriate Parent ID no matter what language tab you’re on.
=> issue: Multilingual FAQ Category w/ Parent

include/class.ticket.php
not sending new ticket alert to account manager in case:
"New ticket alert to Organization Account Manager" selected
"New message alert to Organization Account Manager" not selected
=> Fix bug: send new ticket alert to account manager

bootstrap.php
This commit fixes an issue where using MPDF to print Tickets did not work if the PHP version was < 7.0 because MPDF called the random_int function which is only available for PHP 7.0+. Now, we check the PHP version before printing, and if it is less than 7.0, we use the rand function. If it is >= 7.0, we continue to use the random_int function.
=> Issue: MPDF Export PHP < 7.0

include/class.ticket.php
This addresses issue #4720 where creating tickets via CLI fails to set a status and crashes with an "APC must be enabled" error. This adds a check to see if the APC module is loaded before continuing.
=> issue: APC CLI

include/class.forms.php, include/class.search.php, include/staff/templates/queue-quickfilter.tmpl.php
Make the following quick filters work:
- Assigned
- Assignee
- Department Manager
- Assigned Team
Also, make sure we account for if there are no choices available for a quick filter 
Ex: The helpdesk does not have any teams
=> Quick Filter Fixes:

include/class.staff.php, include/class.ticket.php
This commit fixes an issue where we were not checking the restrictions on Ticket assignment correctly. isAccessLimited returns true if showAssignedOnly is true, so we wouldn't want to negate the isAccessLimited check (that would return true if access is not limited).
Also, if an Agent's access is limited to assigned tickets only, we can return the assigned tickets once we have them without needing to go through any further processing.
Note: queue counts update themselves a little after you toggle the 'Limit ticket access to ONLY assigned tickets' check box. The 'See all tickets in search results, regardless of access' still works correctly as well.
=> Assignment Restriction Issue

include/staff/templates/queue-tickets.tmpl.php
When going to my closed queue, I had the same ticket showing multiple times. This commit moves the call to the distinct method outside of any if statements so that the tickets will always be grouped by their id.
=> Issue: Duplicate Tickets in Closed Queue

include/class.dynamic_forms.php, include/class.forms.php
This commit fixes an issue where checkboxes could not be edited for inline edit or all field edits.
When a BooleanField is directly passed to the to_database method, you are not able to accurately check to see if old != new. To fix this, I added a new getChanges method to the BooleanField class that will first do a comparison on the raw boolean value (true, false) and then get the value needed for the database. I then made sure that we use that new function when editing all fields together as well.
Additionally, I added a getClean method to the BooleanField class so that $this->_clean for the field would be set to either true or NULL depending on if the box is checked or not and would accurately save to the database when calling $form->saveAnswers()
This fixes Issue #4782
=> Issue: Saving Checkbox Values

include/class.thread.php, include/client/templates/thread-export.tmpl.php
This pull adds the ability to choose between ASC or DESC order for the complete thread variable. If `complete_asc` is chosen the system will order the thread in ASC order, if `complete_desc` is chosen the system will order the thread in DESC order. This keeps backwards compatibility with just `complete` as some people might forget to update this for a while.
=> variable: Complete Thread ASC or DESC

include/class.forms.php
This addresses an issue on the forums where having a comma in your number format (instead of periods) would crash the system if using a language pack other than English. (Fix suggested by @rspma on the forums.)
=> issue: Maxfilesize Comma Crash

include/class.config.php, include/class.validator.php, include/client/header.inc.php, include/i18n/en_US/help/tips/settings.system.yaml, include/staff/header.inc.php, include/staff/login.header.php, include/staff/settings-system.inc.php, setup/inc/header.inc.php
Previously, we added a security header to prevent click-jacking called "X-Frame-Options". This introduced an issue with people using osTicket in iFrames on their websites. To mitigate the issue, this updates the security header to allow the site to be framed from specified domains, if none provided we default to 'self'. This adds a new field to General System Settings called "Allow iFrames" where you may enter a comma separated list of domains that the site can be framed on. This also adds a validator for the field to validate the domains and ensure they fit the <host-source> syntax from [Mozilla Developer Docs](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/frame-ancestors#Sources).
=> iframe: Allow Multiple iFrame Domains

include/class.format.php
This addresses an issue where Korean text is stripped from the body. This is due to the `strip_emoticons()` function, as Korean text is in the same unicode range as some of the emojis.
=> oops: Emojis Strip Korean

include/class.thread.php
This addresses an issue introduced with #4737 where using `%{ticket.thread}` causes a fatal error. This is because `ObjectThread->asVar()` returns an object which cannot be converted to a string. This adds a `__tostring()` function to class ThreadEntries so it can be converted to a string properly.
=> oops: Thread Variable Fatal Error

include/class.queue.php
This commit fixes an issue where only the saved export fields would export, whether you checked more fields to export or unchecked some of the saved fields.
For any fields not saved that need to be exported, we need to find their label and then put it in the fields array. For any saved export fields that are unchecked, we need to compare what was checked vs what is saved and then unset the fields that were unchecked.
=> Issue: Choosing Fields to Export

include/class.queue.php
This commit fixes an issue where custom export headings were being set to numeric values rather than field labels.
For exports that are already saved, we can get the heading directly using getHeading. To get the heading for fields that are not already saved as exports, we can use getExportableFields, which will return path => heading.
=> Issue: Ticket Export Headers

include/class.faq.php, include/class.pdf.php, include/mpdf/vendor/mpdf/mpdf/src/Config/ConfigVariables.php
1. Task Exports: This commit fixes the contructor for printing Tasks using MPDF
2. PDF Formatting: This commit fixes an issue where the header of each thread entry did not stretch across the page correctly. This was an unintentional side effect of trying to fix the way HTML tables printed in PDFs.
3. FAQ PDFs: This commit passes the correct values to mPDFWithLocalImages when printing FAQs
=> MPDF Issues

scp/orgs.php
This addresses an issue where clicking Export on an Organization's Tickets will export a file with the filename of 'csv' and no extension. This is due to the variables we are passing to the `saveTickets` function. We are missing a variable called '$fields' that contains a list of fields.
=> issue: Organization Ticket Export No Filename

include/class.forms.php
This addresses issue mentioned in #4071 where the choice field validation is not accepting punctuations. This updates the regex to accept anything the user inputs. This introduces another issue that if the choice contains `:` in the value then it will truncate everything after. This is due to the explode method that explodes on any `:` character. This updates the explode method to return only 2 values which only explodes on one `:` character which returns the full value.
=> issue: Choice Validation Accept Punctuation

include/class.config.php, include/client/header.inc.php, include/staff/header.inc.php, include/staff/login.header.php, setup/inc/header.inc.php
It's all about the single quotes baby! Apparently I can't read; the single quotes are only meant for word options such as `'self'` and `'none'`. When adding single quotes to the `<host-source>` options it takes them literally…too literally. For example, if your options are `'localhost:80 localhost:8080 localhost:8000'` then `'localhost:80` and `localhost:8000'` will be seen as "invalid" due to the single quotes. This removes the single quotes from every line that sets the CSP so all options are valid. This also adds single quotes around the `self` option so it stays valid as well.
=> issue: iFrame Single Quotes

include/class.ticket.php
This addresses an issue where entering a collaborator's email to send ticket email access link throws a fatal error. This is due to the method that checks for tickets with the User's email equal to the email provided. This only checks for User's emails not Collaborator emails. This adds a check for Collaborator emails as well so this will not crash out.
=> issue: sendAccessLink On NULL

include/class.config.php, include/class.validator.php, include/client/header.inc.php, include/i18n/en_US/help/tips/settings.system.yaml, include/staff/header.inc.php, include/staff/settings-system.inc.php
This adds a new feature called ACL that offers the ability to control what IP addresses are allowed to access the Login Page(s). This adds a new textfield to the System Settings to add a comma separated list of IPs. This also adds a checkbox called "Apply To Backend Only" that, if enabled, will only apply the ACL to the Agent Login Page. Lastly, this adds a validator for a simple comma-separated list of IP addresses. (eg. `111.111.111.111, 222.222.222.222, 333.333.333.333`)
If the requester's IP is not in the ACL the system will show an "Access Denied" page. If the requester's IP is in the ACL they will be able to access the Login Page(s) as usual. If the ACL field is left blank anyone will be able to access the User/Agent Login Pages.
=> feature: ACL (Access Control List)

include/class.mailer.php, include/class.usersession.php
This addresses an issue in v1.11 where sending an Access Link via email to a Collaborator fails with fatal error. This is due to the type of User class that is sent to the `Mailer::send()` function. The ClientSession User class is not appropriate for this method, rather, TicketOwner or Collaborator User classes are appropriate. This adds a function called `getSessionUser()` to the ClientSession class so we can retrieve the TicketOwner/Collaborator User class from the session.
=> issue: sendAccessLink On NULL v1.11

client.inc.php, include/client/header.inc.php, include/staff/header.inc.php, scp/staff.inc.php
This moves ACL enforcement from the header files to the `client.inc.php` & `staff.inc.php` files so that AJAX/PJAX may bypass ACL.
=> issue: ACL Move To Inc Files

include/class.pdf.php, include/mpdf/vendor/mpdf/mpdf/src/Config/ConfigVariables.php
Use the psize that is set in the options array since $psize is not in the Task2PDF contructor.
=> MPDF Tasks

include/staff/templates/tasks-actions.tmpl.php, include/staff/ticket-tasks.inc.php, scp/js/scp.js, scp/js/ticket.js
Increase default pjax timeout to 30 seconds to avoid double requests  & reloads.
=> PJAX: Increase default timeout

include/pear/Mail/mimeDecode.php
This commit addresses an issue where pre_replace fails in php 7.x resulting in a ticket with an empty body.
=> Mime Decode - Encoded chars

include/ajax.tickets.php, include/class.forms.php, include/class.osticket.php, include/class.ostsession.php, include/class.queue.php, include/class.search.php, include/class.staff.php, include/class.thread.php, include/cli/modules/i18n.php, setup/test/tests/class.php_analyze.php
Bug fixes and enhancements for v1.11
=> Issues since v1.11 release

include/class.task.php
This addresses an issue where having the `%{task.due_date}` variable in a Task alert template whilst creating a Task with an Assignee causes a fatal error in the backend leaving the Create Task modal spinning forever. This is due to the `getVar()` method for Tasks where the `due_date` case references a non-existing method. This updates the referenced method to an existing method so it gets the correct value and does not cause a fatal error.
=> issue: Task EstDueDate

include/ajax.admin.php, include/staff/templates/queue-sorting.tmpl.php
This addresses an issue reported on the Forum where adding a new Sort Option for Queues without a title fails without error. This is due to the queue-sorting template that uses a new instance of the `QueueSortDataConfigForm` form from a new instance of `QueueSort` rather than the existing form with existing POST data/errors when a POST is submitted. This updates the queue-sorting template to use the already available `$data_form` form instance. This also adds an if statement to set the `$data_form` if one doesn’t exist (this only applies to new modals without a POST).
=> issue: Queue Sort Title No Validation Error

include/class.mailfetch.php
This addresses a typo where we are missing a not operator in class MailFetcher when checking for no `$body` in the fetched attachments. This adds the not operator so that the `if()` statement is properly executed and we correctly set a fake body when there is none.
=> oops: .eml/.msg Missing Not Operator

include/class.search.php, include/class.staff.php, include/staff/templates/queue-tickets.tmpl.php
This commit ensures that an Agent with the 'See all tickets in search results, regardless of access' permission checked can see all Tickets in a search or a saved search, but does NOT see all Tickets within queues.
=> Issue: Tickets Visibility

include/cli/modules/package.php
This addresses an issue where the `package` cli module is leaving out the permissions on files. This causes the final ZIP archive to contain files without permissions meaning the files are un-usable until you restore permissions. This can make life difficult on people trying to install osTicket with minimal knowledge as they wouldn’t know what is wrong.
This is due to the `setExternalAttributesName` method not shifting 16 bits on the file "mode" which will not translate to binary. The file "mode" is the inode protection mode for a file returned by the `stat()` method. It is essentially a decimal representation of a file's permissions. Since "mode" is in decimal format we need to shift by 16 bits to translate it to binary so the archiver understands. Once the mode is translated to binary …
=> cli: Package No File Permissions

include/class.category.php, include/class.faq.php, scp/categories.php, scp/helptopics.php
This commit fixes several issues with how we manage FAQs and related objects.
1. When trying to add a Help Topic to an FAQ, we should add the record to the faq_topic table after saving the faq so that we can accurately retrieve the faq_id
2. When deleting a Help Topic, we need to make sure we're using the topic->delete function rather than deleting based on a QuerySet so that the related FAQ Topics will also be deleted.
3. When deleting a FAQ Category, we need to ensure that we delete all related FAQs and FAQ Topics. To do this, we should use the delete function from the FAQ class first to delete all related FAQs and FAQ Topics and then we should use the Category delete function to delete the remaining Category (remove faqs->expunge from the category->delete function since it we now pass …
=> FAQ Issues

include/cli/modules/package.php
This updates the variable name that determines if the current PHP version is 5.6+ from `$php56` to `$php56plus`. This will help others understand better what the variable is/does.
=> cli: Package Better Wording

include/class.task.php, include/class.thread_actions.php
This fixes an issue where, for task threads, if an agent has the thread edit permission, the agent was neither able to edit his or her own entries, nor the entries of other agents.
=> task: Implement edit of task thread

include/class.dept.php, include/class.ticket.php
If an alert is enabled for only the Department Manager and the Department Recipients field is set to No one, the Department Manager still receives a notification.
If the recipients field is set to no one, nobody should receive an alert regardless of what is checked on the New Ticket Alert selections.
To fix this, we can do a count of what the getMembersForAlerts function returns. This function compares what is set for a Department's group_membership in the database to the ALERTS_DISABLED constant to return a query set of members that should receive an alert. If the count is 0, we know that alerts should be disabled.
=> Issue: Ticket Alerts vs Dept Recipients

include/client/templates/thread-export.tmpl.php
This just removes an unnecessary "`;`" semicolon in `include/client/templates/thread-export.tmpl.php`
=> Double semicolon removed

include/class.dynamic_forms.php
This addresses an issue where New Tickets will fail for Users with a deleted ListItem retained in their Contact Information form. This is due to the system deleting the `list_id` for the ListItem so when we run `getFilterData()` for the User we can't find the list which causes a fatal error later down the line. This adds an OR statement to the `SelectionField::getFilterData()` method to skip said ListItems if no `list_id` is present.
=> issue: Retained Deleted ListItem Errors

account.php
This addresses issue #4898 where a User that clicks the ticket link in an email alert to view the ticket, in that ticket view clicks the link to register for an account, fills out the registration form, and clicks Create will throw a an "Unable to register account. See messages below." error. When the Users get this error there are no messages below so they can't see anything to fix which prevents them from creating an account. This is due to the email field being disabled which means the value is not sent in POST so the system thinks the User sent no email address which throws a hidden "Email field required." error. We disabled the email field to prevent an attacker from accessing the user’s guest login and registering the user with a different email (possibly his own). This sets a POST …
=> issue: Account Registration Throws Errors

include/class.list.php
If you have a custom field that's based on a list and the default value is set to a list item where the extra field is empty ('') instead of NULL, you cannot set the default value back to 'Select a Default'. You CAN set it to other default values
Extra is set to empty if you erase the abbreviation and save it. Should save as NULL instead of empty
Note: for some reason this didn't work
if ($k == 'abbrev' && empty($vars[$k]))
$this->set($v, NULL);
=> Empty extra in list_items

include/class.charset.php
This addresses an issue where emails with `ISO-8859-8-i` character-sets appear as "(empty)" in the system. This is due to `ISO-8859-8-i` not being a valid character-set for `iconv()`. When you pass `ISO-8859-8-i` to `iconv()` you will receive an error similar to `iconv(): Wrong charset, conversion from 'ISO-8859-8-i' to 'UTF-8//IGNORE' is not allowed`. I don’t know why it's not a valid character-set for `iconv()` but the trailing `-i` is used to say "keep the text in logical order instead of visual order". Logical order just means to keep the text in true right-to-left format instead of transcoding the characters to left-to-right format.
This adds a new case to the `Charset::normalize()` switch statement to match against `ISO-XXXX-X-i`. If a character set matches the criteria we will …
=> issue: ISO-8859-8-i Charset Issues

include/class.search.php
This addresses an issue where `IndexOldStuff()` doesn't reindex everything it's supposed to. The reindex leaves out all of the Thread Entries with empty titles or bodies. This is due to the SQL statement that retrieves thread entries. In the SQL statement, we check if the sum of the Thread Entry Title length and the Thread Entry Body length is greater than 0. If so we reindex the entry, otherwise we exclude it. The problem is both ```LENGTH(A1.`title`)``` and ```LENGTH(A1.`body`)``` can return `NULL` and you cannot add `NULL` (a string) to an integer. This updates the SQL to add `IFNULL()` statements around the possible `NULL` values so that if `NULL` we typecast to integer of 0 which can be added to integers successfully.
=> issue: Search Reindexing Thread Entries

include/class.mailfetch.php
In the event that we receive an email where the reply-to header is formatted with the name being an unquoted email, we should correct the name by inserting the quotes.
Incorrect Format:
adriane@enhancesoft.com <adriane@enhancesoft.com>
Correct Format:
"adriane@enhancesoft.com" <adriane@enhancesoft.com>
=> Reformat Incorrect Reply-To Headers

include/class.format.php
This addresses an issue reported by Vincent Monier (Xenos) where posting a single `</div>` tag as a message or response via the UI will break the HTML Thread Tree view. This is due to the `html_balance()` method not cleaning empty div tags. This adds `'div'=>1` to the empty tag array so that any rogue div tag + any empty div tags are properly removed.
=> issue: Rogue Closing div Breaks HTML Thread Tree

setup/inc/class.installer.php
This addresses an issue reported by Aishwarya Iyer where inserting `<img src =x onerror = prompt(1)` into any text field on the install form will execute in the browser after the system is installed and you log in. This is due to us not sanitizing the content before it’s saved in the database. This adds `Format::htmlchars()` to the installer to ensure the text field data is sanitized properly.
=> xss: Install Form

include/mpdf/vendor/mpdf/mpdf/src/Config/ConfigVariables.php
This addresses an issue with Thai fonts (and a few others like Hebrew, Arabic, etc.) where printing a PDF will show square characters instead of the actual content. This is due to `autoScriptToLang` and `autoLangToFont` not being set to `TRUE`. This updates the mPDF config to set the value of `autoScriptToLang` to `TRUE` as this formats the HTML using the lang attribute for the specific language of the content. In addition, this updates the mPDF config to set `autoLangToFont` to `TRUE` as this selects the correct font to use for the specific language of the content.
https://mpdf.github.io/fonts-languages/automatic-font-selection.html
=> issue: PDF Squares Instead Of Text

include/class.export.php, include/class.forms.php, include/class.user.php, include/class.validator.php
This addresses a security issue discovered by Aishwarya Iyer where a User can change their Full Name to a windows formula and when an Agent exports a list of Users containing said User and opens the export file, the formula will be executed on their computer (if it's windows of course). This adds a new validator called `is_formula()` to all text fields disallowing the use of the following characters `= + - @` at the beginning of text. This should mitigate CSV Formula injections for any text field that allows user-input in the system. To further prevent CSV Formula injections this adds an escape mechanism to the Exporter that will escape any content matching the formula regex with a single quote (as mentioned in many posts about this subject).
=> security: CSV Formula Injection

include/class.format.php
This corrects the spelling of `deposition` to `disposition` so that it's correctly utilized.
=> issue: Class Format Disposition Misspelling

include/ajax.thread.php, include/class.thread.php, include/staff/templates/collaborators.tmpl.php, include/staff/templates/task-view.tmpl.php, include/staff/ticket-view.inc.php
This code allows Agents to Manage Collaborators without the page refreshing so that they will not lose any drafts that might not have been saved yet. Instead, adding/removing collaborators will show up instantly in the active collaborators section.
This code also removes the http response from the updateCollaborators function. This triggers collaborators.tmpl.php to correctly update the active collaborators section without needing to refresh the page.
=> Add/Remove Collabs Without Refresh

include/class.validator.php
This addresses an issue where having a new line in a standard, non-richtext textarea field fails on `is_formula` validation. This is due to the regex not running in Dotall mode, which does not match new line characters. Dotall mode makes the dot (`.`) character match anything _including_ new line characters. This adds the `s` flag to the regex so that new lines are properly matched.
=> issue: is_formula Dotall Mode

include/class.file.php
This addresses an issue reported by Aishwarya Iyer where attached HTML files are executed in the browser instead of forcing download in Firefox and IE for Windows specifically. This is caused by an incorrect `Content-Disposition` set in the `AttachmentFile::download` function. Instead of attachments having a disposition of `attachment` (which forces download) they have a disposition of `inline` (which displays the file contents in the browser). This updates the download function to use whatever disposition is passed (for S3 plugin), if none it defaults to `attachment`. In addition, this overwrites the disposition and sets it to `attachment` after the `$bk->sendRedirectURL()` so that S3 attachments still work and the issue of an attacker passing their own disposition is mitigated.
=> security: HTML File Browser Execution (Windows: Firefox/IE)

bootstrap.php
This addresses an issue where if you’re running an outdated version of the 1.12 series, the latest version it shows available is the latest release of the 1.10 series. This updates the `MAJOR_VERSION` variable used to check for the latest release for the series you’re currently on so that it shows the appropriate release.
=> issue: v1.12 Git MAJOR_VERSION

include/class.misc.php, include/class.ticket.php
This addresses an issue where creating a ticket with a Due Date set fails with an error of `Select a time from the list`. This is due to unused variables in the `Ticket::create()` function. This also improves the datetime conversion to GMT by using `Format::parseDateTime()` instead of trying to create a DateTime object directly which also provides a fallback if an incorrect time. This can correctly determine the timezone (if present) and return a proper DateTime object.
=> issue: DatetimeField Remove Unused Vars / Use parseDateTime()

include/class.error.php
This addresses issue #3517 where manage.php file migrate fails when files have size = 0. This is due to the BaseError constructor that call `logError()` on `$ost` without controls if this one is not null.
=> Issue: manage.php file migrate fails when files have size=0

bootstrap.php, include/cli/modules/deploy.php
This addresses an issue where using osTicket from git would show the incorrect git version in `Admin Panel > Dashboard > Information`. This is due to a hardcoded git version of `1.8-git`. This updates `THIS_VERSION` to utilize `MAJOR_VERSION` so that it sets the correct git version. This also updates the `deploy` CLI module to match the same format (example: `1.12-git`).
=> issue: THIS_VERSION Utilize MAJOR_VERSION

include/ajax.staff.php
This addresses an issue reported on the Forum where clicking the "Reset Permissions" action in the Agent Directory shows a blank popup. Inspecting the console shows 500 error and checking the error logs shows `Too few arguments to function` error. This is due to the `RolePermission::__construct()` method expecting 1 parameter but in `ajax.staff.php` we are not passing anything to it. This updates `resetPermissions()` to pass `null` to `RolePermission::__construct()` so that it doesn't complain and error out.
=> issue: Reset Role Permissions

include/staff/tpl.inc.php
For the is_a function, the class name should be in quotation marks to avoid the warning in PHP 7.3
=> Issue: Undefined Constant Warning

include/class.report.php
This addresses an issue reported on the Forum where visiting the Agent Dashboard with no Help Topics in the system completely breaks the Dashboard view and throws a database error `You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ') GROUP BY A1.topic_id' at line 1`. This is due to the statistics code assuming we will always have `$topics` but this is not always the case, as some people rock their helpdesk without a single Help Topic. This adds a check to see if `$topics` is empty and if so, we return the appropriate headers with an empty array as the plot data. This will avoid the database error and show the appropriate Dashboard view with no statistics listed under "Topics" tab.
=> issue: Dashboard No Help Topics Error

include/class.pdf.php, include/class.ticket.php, include/staff/templates/ticket-print.tmpl.php, include/staff/ticket-view.inc.php, scp/tickets.php
This feature adds a new Print option labeled "Thread + Internal Notes + Events" that, when clicked, will print the entire Ticket Thread with Internal Notes AND all of the Thread Events. This also adds a new option in the Ticket Print Options labeled "Print Events". Previous print options only included the Thread only or the Thread + Internal Notes, but people want more! This inserts the events in the correct order just like it is in the Ticket View. The only difference between the PDF Thread Events and the Ticket View Thread Events is the styling. In the Ticket View each event has it's own icon to separate/differentiate them between the others. In the PDF the events will not have their own icons rather their own background to separate/differentiate them.
=> feature: Expanded Print View
