osTicket/osTicket

- include/i18n/en_US/help/tips/staff.department.yaml
Fixes https://github.com/osTicket/osTicket-1.8/issues/1673
> Fix SLA link in help tips

- include/class.ticket.php
Fixes `setStatusId` bug introduced by 8bdfa04f
> oops: bug fix

- include/class.banlist.php
- include/class.canned.php
- include/class.filter.php
- include/class.mailfetch.php
- include/class.ticket.php
- include/i18n/en_US/filter.yaml
This pull request addresses several regression issues introduced by pull request #1349 
Refactor filter.yaml and related code base for installer to load banlist filter
Move isBanned routine to banlist class and make it banlist specific
Refactor how canned responses get list of attached filters
> oops: ticket filters

- include/class.page.php
- include/class.staff.php
- include/upgrader/streams/core/1ee831c8-36f6b328.task.php
- include/upgrader/streams/core/8f99b8bf-03ff59bf.task.php
- include/upgrader/streams/core/934954de-f1ccd3bb.task.php
- include/upgrader/streams/core/b26f29a6-1ee831c8.task.php
- include/upgrader/streams/core/d51f303a-dad45ca2.task.php
- include/upgrader/streams/core/dad45ca2-61c9d5d7.task.php
Make the upgrader play nice when loading latest yaml files while upgrading from versions prior to v1.8.
> upgrader: Support upgrading from 1.7 to v1.9.6

- include/class.api.php
- include/class.charset.php
- include/class.format.php
- include/class.mailfetch.php
- include/class.mailparse.php
- include/class.translation.php
- include/tnef_decoder.php
This pull request adds a cleanup util for bogus and invalid charsets, mostly added by a nameless company out of Redmond, WA.
> charset: Normalize charsets

- include/class.thread.php
http://www.osticket.com/forum/discussion/84718/bug-report-orphans-in-ost-ticket-collaborator#latest
> thread: Remove collaborators when removing the thread

- include/class.dynamic_forms.php
- include/class.forms.php
- include/class.list.php
Also add support for filtering by list item abbreviation (extra) field
> filter: Fix filtering by list item properties

- include/class.setup.php
Log cleanup SQL errors during upgrade
> upgrader: Log SQL errors

- include/client/login.inc.php
See the discussion at https://github.com/osTicket/osTicket-1.8/issues/1777 for details
> fixes #1777

- include/ajax.tickets.php
- include/class.lock.php
- include/staff/footer.inc.php
- include/staff/ticket-view.inc.php
- js/redactor-osticket.js
- scp/js/scp.js
- scp/js/ticket.js
- scp/tickets.php
Also, add warning popup when lock is about to expire and allow the user to attempt to renew the lock. Also, connect the keyup callback for redactor to the autoLock.handleEvent for greater update of the lock, and also deadband the lock to every 10 seconds.
> lock: Sync lockCode input with lock renew

- css/redactor.css
- include/class.dynamic_forms.php
- include/client/templates/dynamic-form.tmpl.php
- include/staff/dynamic-form.inc.php
- include/staff/templates/dynamic-field-config.tmpl.php
- include/staff/templates/dynamic-form-simple.tmpl.php
- include/staff/templates/dynamic-form.tmpl.php
- include/staff/templates/inline-form.tmpl.php
- include/staff/templates/simple-form.tmpl.php
- include/upgrader/streams/core/5cd0a25a-2d590ffa.task.php
> forms: Allow HTML in the help text (hint)

- include/class.dynamic_forms.php
- include/class.forms.php
Get all dynamic fields in DynamicFormEntry, not just fields with answers
> Dynamic form entry fields  

- include/ajax.content.php
> docs: Add variables for thread to template popout

- scp/helptopics.php
Corrected to typos in scp/helptopics.php. One was mentioned in https://github.com/osTicket/osTicket-1.8/issues/1819
> Fixed typos in scp/helptopics.php

- include/class.ticket.php
> thread: Log remote IP for staff replies and notes

- tickets.php
> files: Clear attachment box after posting a response

- include/class.ticket.php
> cdata: Drop ticket cdata on delete

- .gitignore
- include/class.ticket.php
Clear the overdue status of a ticket when it's closed.  Fixes #1736
> Clear overdue on close

- include/class.config.php
- include/i18n/en_US/help/tips/settings.kb.yaml
- include/staff/settings-kb.inc.php
> kb: Add setting to enable only for authenticated clients

- include/staff/faq.inc.php
Maybe fixes #534
Maybe fixes #74
> faq: Show proper internal/public category in drop-down

- setup/cli/modules/i18n.php
This patch allows for signing language packs and plugins via the command line (which was already implemented), but also allows for signing multiple files (include/i18n/*.phar), and supports registering the generated seal in DNS immediately.
> i18n: Automate dns signature publishing for language packs

- include/class.thread.php
- include/class.ticket.php
> collabs: Skip activity notice if collabs included in Cc header

- include/staff/tickets.inc.php
Support filtering search results by uid.
> bug: Support quick user id filtering

- include/class.forms.php
> forms: Fix unset of all checkboxes on a form

- include/staff/tickets.inc.php
Maybe fixes #1832
Maybe fixes #1573
Maybe fixes #993
> search: Fix search for unassigned tickets

- include/class.user.php
- include/mysqli.php
- setup/cli/modules/class.module.php
- setup/cli/modules/cron.php
- setup/cli/modules/user.php
This adds the ability to find, activate, lock, and optionally send a password-reset email to one ore more users in the help desk.
> cli: user: Add list, activate, lock features

- include/ajax.tickets.php
- include/class.export.php
- include/class.format.php
- include/class.orm.php
- include/class.search.php
- include/staff/templates/tickets.tmpl.php
- include/staff/tickets.inc.php
- scp/css/scp.css
- scp/js/scp.js
Also, significantly speed the ticket queue loading
> queue: Make sorting options relevant to the current queue

- include/class.thread.php
The %ticket_email_info table needs an index on thread_id. This is done in the `develop-next` branch; however, this patch helps alleviate performance issues on the main branch until the `develop-next` branch is collapsed for main line development.
> thread: Defer loading email header information

- scp/js/ticket.js
Maybe fixes #1896
Maybe fixes #984
Maybe fixes #484
> lock: Disable navigation warning if not using the lock feature

- include/ajax.forms.php
List items are only unique within the list.
> bug: Consider list when looking up list item

- scp/css/scp.css
> ui: Dialog and overlay appear over tip boxes

- bootstrap.php
- include/client/header.inc.php
- include/staff/header.inc.php
> i18n: Ensure UTF-8 is used as the request encoding

- include/class.mailfetch.php
- include/class.mailparse.php
- include/class.thread.php
> thread: Avoid crash with multiple Message-ID headers

- include/class.dynamic_forms.php
- include/class.forms.php
- include/class.organization.php
- include/class.user.php
- include/client/templates/dynamic-form.tmpl.php
- include/client/view.inc.php
- include/staff/orgs.inc.php
- include/staff/ticket-edit.inc.php
- include/staff/users.inc.php
- scp/js/scp.js
* Fix saving of some custom data when adding a new user
* Fix saving of some custom data when adding a new organization
* Fix update of organization custom data
* Fix missing media on popup dialogs for some fields
* Delete custom data when removing organizations
* Remove attachment entries from %attachment table when removing data for file upload fields
Fixes #1934
> Fix several issues with user directory objects

- include/staff/dynamic-list.inc.php
I Added __() function for not translated words.
> fix translation for "Add new list"

- include/tnef_decoder.php
This addresses a few processing bugs with the TNEF engine including incorrect property length for a couple properties declared previously.
> tnef: Fix various TNEF processing issues

- index.php
Checks whether user is logged in so it directs you to tickets.php instead of view.php
> Logged user fix

- include/ajax.content.php
- include/class.mailer.php
- include/class.orm.php
- include/class.role.php
- include/class.thread.php
- include/class.thread_actions.php
- include/class.ticket.php
- include/staff/templates/thread-entry-edit.tmpl.php
- include/staff/templates/thread-entry-resend.tmpl.php
- include/staff/templates/thread-entry-view.tmpl.php
- include/staff/ticket-view.inc.php
- include/staff/tickets.inc.php
- js/redactor-osticket.js
- scp/css/dropdown.css
- scp/css/scp.css
- scp/js/scp.js
- scp/roles.php
Threads can be edited by marking the original as hidden and setting it's PID to the id of the new entry. The new entry has cloned data from the original and sets the `updated` timestamp to reflect the time of last edit. An edited flag is added to the new entry to reflect its origin.
This patch suggests that agents can edit their own posts, department managers can edit posts while the ticket is in their department, and that help desk admins can edit anything. Perhaps this should be yet another role privilege.
If a post is edited more than once, only the most recent edit is kept. This is not strictly required by the data model, but avoids the possibility of significant recursion to find a thread's complete history.
> Add concept of thread editing

- include/class.organization.php
> orgs: Touch `updated` time when custom data is updated

- include/staff/profile.inc.php
> include: Fix typo

- include/staff/ticket-view.inc.php
- include/staff/tickets.inc.php
- scp/css/scp.css
- scp/js/scp.js
This adds a floating bar to the screen when scrolling further down in the ticket queue or the ticket view pages.
> ui: Add floating bar to make ticket options more accessible

- include/class.dynamic_forms.php
- include/class.list.php
This adds ability to delete form properties on list deletion.
> forms: Add ability to delete properties form

- include/class.orm.php
- include/class.staff.php
- include/class.task.php
- include/class.ticket.php
- include/class.user.php
This is one of the last milestones for osTicket on an ORM. Unfortunately, it doesn't make any remarkable speed increases at the moment.
*This also adds model inheritance and meta-data merging for ORM models.*
> orm: Port Ticket class to ORM

- assets/default/css/theme.css
- include/class.dynamic_forms.php
- include/class.forms.php
- include/client/templates/dynamic-form.tmpl.php
- scp/css/scp.css
Support ability to include attachments to FreeTextField.
> Add attachments support to FreeTextField

- include/ajax.reports.php
Provide ability to set foreign primary key.
> bug: Fix reports bugs

- include/class.thread.php
- include/client/templates/thread-entries.tmpl.php
- include/client/view.inc.php
- include/staff/templates/thread-entries.tmpl.php
- include/staff/ticket-view.inc.php
- scp/js/thread.js
- scp/js/ticket.js
- scp/tasks.php
- scp/tickets.php
This adds the concept of independent multi-thread rendering.
> thread: Multi-thread rendering

- include/class.forms.php
- include/class.misc.php
- include/class.orm.php
- include/class.search.php
- include/staff/templates/advanced-search-field.tmpl.php
- include/staff/templates/advanced-search.tmpl.php
- include/staff/tickets.inc.php
- scp/css/scp.css
* orm: Correctly label correlated query joins via sub-queries
* orm: Fixup formatting of dates in queries
* orm: Fixup mangling of parameter values with colons in sub-queries
* misc: Fixup incorrect offset calculation in Misc::dbtime()
* forms: search: Add ability to describe a field search
* search: Fix crash searching by ticket due date
* search: Fix wrong results if searching by a date field (unix epoch was not converted to MySQL date format)
* search: Fix wrong results searching by date == or !=
> search: Fix several things related to advanced search

- include/class.dynamic_forms.php
This fixes a regression where custom data for new users is not saved on submission
> oops: Fix missing data from new form entries

- include/class.sla.php
- include/class.thread.php
- include/class.ticket.php
- include/class.user.php
- include/staff/templates/status-options.tmpl.php
- include/staff/templates/ticket-status.tmpl.php
> events: Add events for help topic changes

- include/staff/tasks.inc.php
- include/staff/templates/task-view.tmpl.php
- include/staff/templates/tasks-actions.tmpl.php
- include/staff/ticket-tasks.inc.php
- include/staff/ticket-view.inc.php
- include/staff/tickets.inc.php
- scp/js/ticket.js
> v1.10 Review

- include/class.forms.php
This pull request addresses potential XSS vulnerability due to un-sanitized user inputs on field configuration.
> bug: Sanitize choices options (Back port)

- include/class.forms.php
- include/class.task.php
- include/staff/tasks.inc.php
- include/staff/templates/task-view.tmpl.php
- include/staff/ticket-tasks.inc.php
- include/staff/tickets.inc.php
> v1.10 Bug Fixes

- include/staff/templates/task-preview.tmpl.php
- include/staff/ticket-tasks.inc.php
Restrict view access depending on agent's perm.
> tasks: Ticket tasks access

- include/class.canned.php
> canned: Show department-specific canned responses

- include/client/templates/thread-entry.tmpl.php
- login.php
- scp/css/scp.css
> csrf: Fix CRSF violation on client login

- include/ajax.forms.php
- include/class.forms.php
- include/class.list.php
- include/class.util.php
- include/staff/dynamic-list.inc.php
- include/staff/templates/list-item-properties.tmpl.php
- include/staff/templates/list-item-row.tmpl.php
- include/staff/templates/list-items.tmpl.php
- scp/js/scp.js
- scp/lists.php
This patch shores up the new list management feature with the custom list handler feature written to support lists being saved in a table other than %list_item, namely the built-in ticket status list.
Fixes #2292
> list: Fix add and edit for "Ticket Status" list

- include/class.auth.php
- include/class.import.php
- include/class.staff.php
- include/class.user.php
- include/cli/modules/agent.php
- include/cli/modules/user.php
Also add import / export for agents via CLI
> Add unified CSV importing support

- include/class.timezone.php
> db: Fix timezone detection on Windows

- include/client/tickets.inc.php
> search: Fix ticket number search on client portal

- include/staff/tickets.inc.php
This reverts commit c4ace2d53af4b2a792c92c8e0523e40adc857366.
Fixes #2310
> Revert "db: Fix ticket queue counts for large datasets"

- include/cli/modules/i18n.php
This adds an option to the `i18n` cli module which finds very similar translatable phrases. The hope is to use this to eliminate phrases which are supposed to be duplicated and reused.
Here's the preliminary output of the script:
```
$ php manage.php i18n similar
...
'%1$d of %1$d %3$s deleted' (scp/forms.php:94) and '%1$d of %2$d %3$s deleted' (scp/apikeys.php:89)
'%1$d of %2$d %3$s deleted' (scp/apikeys.php:89) and '%1$d of %2$d %s deleted' (scp/filters.php:97)
'%1$d of %2$d %3$s disabled' (scp/apikeys.php:72) and '%1$d of %2$d %s disabled' (scp/canned.php:126)
'%1$d of %2$d %3$s enabled' (scp/apikeys.php:57) and '%1$d of %2$d %s enabled' (scp/canned.php:111)
'%1$d of %2$d %3$s made PUBLIC' (scp/categories.php:70) and '%1$d of %2$d %s made PUBLIC' (scp/departments.php:65) …
```
> i18n: Add option to find similar translations

- scp/js/ticket.js
Instead, locking would stay active and would warn you about expiring lock after navigating away from a locked object.
Fixes #2343
> lock: Fix missing shutdown on navigation

- include/class.i18n.php
- include/class.topic.php
> topic: Sort localized list case insensitively

- include/class.forms.php
> search: Fix `is` advanced search match

- include/class.dept.php
- include/class.filter_action.php
- scp/js/scp.js
> dept: Fix incorrect SQL removing a department

- include/class.task.php
- include/class.ticket.php
> Fix incorrect usage of department members for alerts

- scp/staff.php
> agent: Add missing perm for view all agents' stats

- include/ajax.tickets.php
- include/class.task.php
- include/class.ticket.php
- include/staff/templates/dynamic-field-config.tmpl.php
- include/staff/templates/task-view.tmpl.php
- include/staff/ticket-view.inc.php
- Tickets cannot be closed when open task(s) exists 
- Tickets/Tasks cannot be closed when required field are missing data
- Add isCloseable routine to ticket/task classes
> Add restrictions to ticket/task closure

- include/client/templates/sidebar.tmpl.php
> ui: malformed featured FAQ URL in sidebar

- scp/js/scp.js
> bug: Not every form has action attr.

- include/staff/templates/task-view.tmpl.php
> bug: Task print

- include/staff/tasks.inc.php
- include/staff/templates/queue-sort.tmpl.php
- include/staff/tickets.inc.php
Utilize the same template for tickets and tasks queues
> Queue sort template

- include/class.dept.php
- include/class.i18n.php
- include/class.topic.php
- include/i18n/en_US/help_topic.yaml
Department create now considers the possibility of preset id (primary key)
Default help topic routing to floating system's default department
PS: The bug only affects users using DB cluster.
> bug: Zombie tickets

- include/class.ticket.php
> sla: Capture current sla before setting new one

- include/ajax.orgs.php
> orgs: Show user search box adding user to org

- include/class.forms.php
- include/class.search.php
> search: Add search for closed date

- include/staff/templates/task-view.tmpl.php
> UI fix for delete button highlight - 2456

- include/staff/helptopic.inc.php
- include/staff/templates/form-manage.tmpl.php
> forms: Forbid adding deleted forms to topics, form management

- include/class.lock.php
> lock: Fix lock timing if php and db use different time zones

- include/client/header.inc.php
> Send header information before output. Fixes #2554

- include/class.timezone.php
> db: Forbid static zones like 'CDT'

- scp/css/scp.css
#2557 Avatar height issue in Safari.
> Fix for issue #2557

- include/staff/category.inc.php
- include/staff/dynamic-form.inc.php
- include/staff/faq.inc.php
- include/staff/page.inc.php
- include/staff/templates/content-manage.tmpl.php
> i18n: Use horizontal, alt tabs for translatable content tabs

- include/class.search.php
As currently written, if a full text query is attempted in BOOLEAN mode and the query cannot be compiled by MySQL, it causes an OrmException and a crash. This patch adds a more straight-forward and comprehensive grammer-based approach to checking for valid boolean syntax.
> search: Try harder to match MySQL full text boolean query

- account.php
- include/class.forms.php
- include/class.mailfetch.php
Just wanted for an opportunity to review file upload merge conflict changes - 8f18983
> Merge develop to develop-next

- include/class.orm.php
- include/class.ticket.php
- include/staff/templates/tickets.tmpl.php
- include/staff/user-view.inc.php
- scp/orgs.php
- scp/users.php
This PR improves up on ticket related features in User Directory.
* Pagenate tickets listing
* Include tickets the user is a collaborator in User > Tickets
* Add ability to export user's/org's tickets
> User Directory Tickets

- scp/css/scp.css
> Form style browser fix.

- include/class.canned.php
- include/class.forms.php
This pull request addresses regression brought about by PR #2618.
> White-list canned attachments

- include/class.filter_action.php
- include/class.thread.php
- include/class.ticket.php
- include/staff/staffmembers.inc.php
- include/staff/teams.inc.php
- include/staff/ticket-open.inc.php
- include/staff/ticket-view.inc.php
Miscellaneous bugfixes for v1.10
> Misc. bugfixes for v1.10

- include/class.staff.php
> bug: Agents Signature & Timezone dropped on update

- include/class.user.php
Fix forms mixup bug that nulled users' name for existing users on CSV import. GUI update worked as expected only because of the magic $_POST variable.
> bug: CSV User import

- include/class.forms.php
- include/class.thread.php
- include/class.ticket.php
- scp/tickets.php
- tickets.php
Let textarea widgets parse and clean input based on configured text format.
Add generic cleanup routine to ThreadEntryBody class
Clean response/note textarea inputs that are not handled via form api.
> Textarea input cleanup

- tickets.php
> Fix for #2757

- include/i18n/en_US/help/tips/staff.agent.yaml
Language might need some editing, but this will fix issue #2675.
> Added primary role tag to agent page

- css/redactor.css
- include/ajax.forms.php
- include/class.import.php
- include/class.list.php
- scp/lists.php
Use CsvImporter util to importing items
Fix items search
> Fix list import

- include/client/open.inc.php
Allows topicId to be specified as a URL parameter when opening a ticket.
> Patch so that topicId can be specified in $_GET

- include/class.forms.php
- include/class.list.php
Allow changing/saving properties on internal ticket statuses, with the exception of the state.
> Ticket Status Properties

- include/class.file.php
- include/class.osticket.php
- include/cli/cli.inc.php
- include/cli/modules/file.php
This patch ports the `file` cli module to work with the v1.10 codebase
> cli: Fix issues with `file` module on v1.10

- include/class.config.php
This migrates the Config classes to use the ORM.
Fixes #2751
> orm: Migrate Config to ORM

- include/ajax.tickets.php
- include/class.staff.php
- include/i18n/en_US/help/tips/staff.agent.yaml
- include/staff/staff.inc.php
- include/staff/ticket-view.inc.php
This is a rebase of #2772 using a checkbox option rather than separate role selection for a role used in such an edge case
> role: Add option to use primary role on assignment

- include/ajax.forms.php
- include/ajax.orgs.php
- include/ajax.tickets.php
- include/ajax.users.php
- include/class.auth.php
- include/class.client.php
- include/class.config.php
- include/class.export.php
- include/class.filter_action.php
- include/class.format.php
- include/class.i18n.php
- include/class.orm.php
- include/class.thread.php
- include/class.ticket.php
- include/class.topic.php
- include/class.user.php
- include/html2text.php
- include/staff/plugin.inc.php
- include/staff/tickets.inc.php
- scp/css/scp.css
- setup/test/tests/stubs.php
PR for bug fixes... do not merge.
> v1.10 Fixes

- bootstrap.php
- include/class.dynamic_forms.php
- include/class.export.php
- include/class.organization.php
- include/class.ticket.php
- include/class.user.php
- include/staff/orgs.inc.php
- include/staff/users.inc.php
- scp/orgs.php
- scp/users.php
* Fix users export
* Fix orgs export
* Convert orgs list page to ORM
> Users & Orgs export

- include/ajax.users.php
- include/class.auth.php
- include/class.misc.php
> v1.10 rc2 issues

- include/staff/staff.inc.php
Fix for both:
https://github.com/osTicket/osTicket-1.8/issues/2574
https://github.com/osTicket/osTicket-1.8/issues/2672
> Fix for issue 2574 and 2672

- login.php
Consider the destination clicked prior to SSO authentication.
Full credit to @jdelhome3578  PR #2612  simply rebased to drop extra merge commits.
> login: Client SSO Destination

- include/class.topic.php
> Bug: Show help topic specific thank-you page

- include/class.config.php
Make config items caching class instance based.
> Config  items cache

- include/staff/helptopics.inc.php
> oops: Fix manual sort on help topic admin listing page

- include/class.orm.php
- include/staff/ticket-view.inc.php
Use org_id to filter users to update on organization deletion.
> org: Remove users from deleted org.

- include/class.orm.php
> orm: Remove references to the retired slot feature

- include/class.forms.php
- include/class.orm.php
* Use file id instead of attachment id to unset new
* Get new files objects as array
> files: FileUploadWidget render

- include/class.ostsession.php
Session backend issues update via write on new session which caused assertion to fail.
> Session: Create SessionData object on demand

- include/class.dept.php
- include/class.staff.php
- include/staff/department.inc.php
- include/staff/staff.inc.php
This PR addresses a bug in department membership check and also adds a few enhancements.
__Todo__
> Department  Access and Membership

- include/class.mailer.php
Mailer might not have email object set. Regression for commit dcfa5527
> email:  Regression for commit #dcfa5527

- bootstrap.php
Reverts osTicket/osTicket#3168
> Revert "i18n: Ensure UTF-8 locale is set"

- README.md
Update links and references to updated repository name.
> Update references in README.md

- setup/inc/file-unclean.inc.php
Fixed spelling on the already installed page.
> Fix spelling error

- include/ajax.thread.php
- include/class.thread.php
- include/staff/ticket-view.inc.php
- scp/js/scp.js
Fix a bug where it was impossible to disable ALL collaborators
Change recipients active/total count on update
> collabs: Thread Collaborators Update

- include/i18n/en_US/templates/email/ticket.autoreply.yaml
Updated to fix typo "information" on line 36
> Updated ticket.autoreply.yaml

- include/staff/tickets.inc.php
> oops: Fix join for sorting tickets by priority column

- include/client/tickets.inc.php
This fixes sorting and total ticket count.
> Fix issue #3268

- include/client/tickets.inc.php
Refactor PR #3410 to drop extra errant commits. All credit to @jdelhome3578
> Default Tickets Sort

- include/client/header.inc.php
- include/staff/login.header.php
Removes "user-scalable=no" option on the User Portal to let users on mobile devices zoom in and out.
> Feature / User Portal Mobile Scalability (Zoom)

- include/class.task.php
- include/class.template.php
This also fixes a couple missing translations for some template save errors.
Maybe fixes #3190
> tasks: Add template link to the ticket page

- include/ajax.tickets.php
- include/class.ticket.php
> collabs: Fix logging of collaborator emails in ticket thread

- include/client/kb-categories.inc.php
- index.php
Adding possibility to use translations for some texts on clients homepage and clients main knowledgebase page.
> Translation issues on homepage and kb page

- include/ajax.forms.php
> lists: Fix update of ticket status name

- file.php
- include/class.canned.php
- include/class.dept.php
- include/class.dynamic_forms.php
- include/class.filter.php
- include/class.forms.php
- include/class.i18n.php
- include/class.orm.php
- include/class.page.php
- include/class.search.php
- include/class.task.php
- include/class.ticket.php
- include/pear/Net/SMTP.php
- include/staff/faq-categories.inc.php
- include/staff/staff.inc.php
- include/staff/staffmembers.inc.php
- login.php
> v1.10-rc.3 Bug Fixes

- include/class.thread.php
Handle cases where email email doesn't have a message-id - regression in PR #3276
> Passive Threading Revisited

- include/class.sequence.php
- include/upgrader/streams/core/8f99b8bf-03ff59bf.task.php
Fixes [upgrade crash] (https://github.com/osTicket/osTicket/issues/3399#issuecomment-256115832) in issue #3399
> upgrader: Fix crash on SequenceLoader

- scp/js/upgrader.js
This checks to make sure string translation function '__()' is defined.
> upgrader: Fix undefined function

- include/class.filter_action.php
- include/class.ticket.php
Fix case where filter applying 'Use Reply-To Email' filter action triggers a reprocessing loop that exhausts php memory.
> Ticket Filter Memory Leak

- include/staff/ticket-view.inc.php
Display Loading Overlay when posting a response or a note to a ticket. This is to add to @JediKev PR #3426
> Loading Overlay

- include/staff/staff.inc.php
Changes 'Permisions' to the correct spelling 'Permissions'.
> Fixes typo

- include/staff/ticket-view.inc.php
A small error on line 871 in include/staff/ticket-view.inc.php
> Typo error missing a parenteses

- include/class.dept.php
Move orphaned tasks on department deletion to the default department
> Orphaned Tasks on Dept. Deletion

- include/ajax.forms.php
Encode html entities of cached form data
> xss: Cached forms data

- include/staff/templates/task-view.tmpl.php
Don't display the Close Task option if the current user can't close it...
> Check permissions before displaying Close Task

- include/staff/directory.inc.php
This addresses a vulnerability where an Agent can perform XSS via the
Agent Directory’s REQUEST query string. This sanitizes the request params
so the code will be escaped and not executed in the browser.
> xss: Prevent Agent Directory XSS

- include/class.file.php
This addresses an issue that was introduced by a previous attempt to
address the orphaned file query. The previous attempt addressed the
original issue but slowed database performance so this addresses the
performance issue.
> issue: Orphaned File Query Rewrite

- include/client/tickets.inc.php
- js/redactor-osticket.js
- Add space between column headers and sort arrow
- Fix sorting by 'Subject' column
- Fix redactor issues with 'Reset' button
- Make sure text within redactor is cleared correctly
- Make sure we don't keep attachments if Reset
- Make sure redactor is reinitialized where needed
This will fix the Reset button everywhere else as well as in the Web Portal.
> Web Portal Fixes:

- include/class.thread.php
This commit adds an additional check for Team referrals in the isReferred method so that it is handled in the same way Staff and Departments are handled.
> Team Referral Check

- include/class.ticket.php
Enable/Disable Collaborators based on which Collaborators are in the 'Select Active Collaborators' box
> Implement 'Select Active Collaborators':

- include/class.queue.php
This commit adds 'TicketStatus / Status Name' to the main search criteria list for advanced searching.
> Advanced Search: TicketStatus / Status Name

- include/class.role.php
This alphabetizes all Role and Staff Permissions.
> perms: Alphabetize Role/Staff Permissions

- include/class.forms.php
- include/staff/ticket-view.inc.php
This addresses an issue where FileUploadFields on the ticket header is not displaying all attachments in the field.
> issue: Multiple File Display

- include/class.config.php
- include/class.cron.php
This adds functionality to clean expired password reset tokens on cron runs.
> cron: Clean Expired Passwd Resets

- include/class.forms.php
- include/class.mailer.php
- include/class.variable.php
This commit addresses the root cause of an issue commit 96892bebff (now reverted) attempted to solve by providing consistency between getFiles vs getAttachments
> Make getFiles() return files

- include/staff/templates/status-options.tmpl.php
- include/staff/templates/tickets-actions.tmpl.php
- include/staff/ticket-view.inc.php
This improves accessibility by adding screen readable labels to ticket actions that don’t already have them.
> accessibility: Screen Readable Actions

- include/ajax.tickets.php
This commit stores internal notes if an Agent includes one while creating a Thread Referral.
> Implement Referral Internal Notes

- include/staff/templates/queue-navigation.tmpl.php
This addresses an issue where personal queues are duplicated in the main queue sub-list.
> issue: Duplicate Personal Queues

- include/class.filter.php
- include/class.orm.php
- include/class.queue.php
- include/class.thread.php
- include/class.ticket.php
- include/client/footer.inc.php
- include/staff/footer.inc.php
Collection of fixes for v1.11.x
> Misc. Fixes

- include/class.forms.php
This addresses an issue introduced with #4426 that references an undefined class.
> oops: Class GenericAttachment Not Found

- include/class.ticket.php
This addresses a careless copy/paste mistake made with 4496
> Oops: Creating Tickets with Attachments

- include/class.forms.php
- include/class.misc.php
Add support for periods to `DateTimeField` allowing the search on range of dates based on set periods like 'Today', 'This Quarter' or 'Last Week' etc.
> Add period to DateTimeField

- include/class.file.php
This commit ensures that we use the correct disposition for downloading files.
> File Disposition

- include/ajax.search.php
- include/class.search.php
- include/staff/templates/queue-tickets.tmpl.php
- include/upgrader/done.inc.php
- scp/autocron.php
This commits adds fallback for queue counts failures and improves caching mechanism.
> Queue counts

- include/ajax.forms.php
- include/ajax.orgs.php
- include/ajax.users.php
- include/class.dynamic_forms.php
- include/class.forms.php
- include/class.ticket.php
- include/class.user.php
- include/client/open.inc.php
- include/client/templates/dynamic-form.tmpl.php
- include/staff/templates/dynamic-form.tmpl.php
- include/staff/templates/user-lookup.tmpl.php
- include/staff/ticket-view.inc.php
- scp/js/scp.js
- tickets.php
This commit addresses inconsistencies on how field edit rights and visibility are are handled.
> Forms: Field Permissions

- include/class.file.php
- include/class.thread.php
- include/client/templates/thread-export.tmpl.php
Support using %{ticket.thread} to export the entire ticket thread correspondence between agents and end users (owner + collaborators).
> feature: Complete Thread Variable

- include/class.filter.php
- include/class.filter_action.php
- scp/filters.php
- Make sure we only set Filter Flags if they need to be changed (don't update them every time we save)
- Make sure we sure we use the email_id if we have actually set it. Otherwise, we lose what should be set for the Target Channel
> Issue: Filters

- include/staff/templates/queue-tickets.tmpl.php
This commit ensures that we do not return duplicate results when searching for Tickets with an Advanced Search that contains keywords.
> Issue: Duplicate Search Results

- include/class.forms.php
Fixes an unexpected side effect of Pull Request #4652
> Oops: Modify 0 in Short Answer Field Fix

- include/ajax.forms.php
This addresses an issue where creating a ticket as an agent and selecting a Help Topic does not show the Issue Summary or Issue Details fields. This is due to us passing 3 parameters instead of 1 as an array. This combines the params in one array and only passes the array as a param.
> issue: New Ticket Field Permissions

- include/ajax.tickets.php
- include/class.export.php
- include/class.format.php
- include/class.forms.php
- include/class.queue.php
- include/class.staff.php
- include/class.thread.php
- include/class.ticket.php
This commit includes several final fixes in general that needed to be made.
> Final Fixes:

- include/ajax.tickets.php
- include/class.forms.php
- include/class.misc.php
- include/staff/templates/dynamic-form.tmpl.php
- include/staff/templates/queue-quickfilter.tmpl.php
- include/staff/templates/tasks-queue-sort.tmpl.php
- include/staff/ticket-open.inc.php
- setup/test/tests/stubs.php
This addresses all the issues found in the final round of testing.
> oops: Last Fixes

- WHATSNEW.md
This adds the changelog for 1.10.5 maintenance release
> changelog: 1.10.5

- include/client/open.inc.php
This addresses an issue where the client-side forms are not rendering correctly. This is due to updating the render() functions but not updating everywhere they are used.
> issue: Client-Side Forms

- include/staff/footer.inc.php
- include/staff/templates/queue-column.tmpl.php
- scp/js/scp.js
This is a continuation of the conversation from #4707
> queues: Fix compatibility issues with newer jQuery

- include/ajax.forms.php
- include/ajax.users.php
- include/class.crypto.php
- include/class.dynamic_forms.php
- include/class.export.php
- include/class.filter.php
- include/class.forms.php
- include/class.mailparse.php
- include/client/edit.inc.php
- include/client/open.inc.php
- include/client/profile.inc.php
- include/client/register.inc.php
- include/staff/templates/org-lookup.tmpl.php
- include/staff/templates/user-lookup.tmpl.php
- include/staff/ticket-edit.inc.php
- setup/test/tests/class.test.php
- setup/test/tests/stubs.php
- setup/test/tests/test.extra-whitespace.php
- setup/test/tests/test.mail-parse.php
- setup/test/tests/test.signals.php
- setup/test/tests/test.syntax.php
- setup/test/tests/test.undefinedmethods.php
- setup/test/tests/test.var-dump.php
This commit gets rid of PHP warnings. Additionally, it updates the lint tests to be more accurate.
> Lint Fixes

- css/jquery-ui-timepicker-addon.css
- include/class.format.php
- include/class.forms.php
- include/class.misc.php
- include/class.ticket.php
- include/client/header.inc.php
- include/staff/footer.inc.php
- include/staff/header.inc.php
- include/staff/ticket-edit.inc.php
- include/staff/ticket-open.inc.php
- js/jquery-ui-sliderAccess.js
- js/jquery-ui-timepicker-addon.js
- js/osticket.js
- scp/js/scp.js
Use datetime picker (jquery-ui-timepicker-addon) for Datetime fields with time selection.
The PR also makes sure the front-end returns ISO formatted date/time to standardize how dates are handled and fixes javascript date format translation from php formats.
> Datetime picker

- README.md
Last one I promise ;) This addresses the sizing issue of the logo in the `README.md` file.
> issue: README.md Image Size

- README.md
> Update osTicket Requirements
